In [43]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

def load_df(file_name):
    df = pd.read_excel(file_name, sheet_name='Sheet 1')
    df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
    df.replace(':', np.nan, inplace=True)
    df.index = df.iloc[:, 0]
    df.drop(df.columns[[0]], axis=1, inplace=True)
    for i in df.columns[:]:
        df[i] = df[i].apply(pd.to_numeric, errors="coerce")
    df.interpolate(method='linear', inplace=True, axis = 1)
    return df

def create_per_employeer(GDP_df, HW_df, employees_df):
    ''' This is a function to create a dataframe with the per-employee GDP and per hour worked '''
    cols =(list(set(GDP_df.columns) and set(employees_df.columns) and set(HW_df.columns)))
    cols.sort()
    idx = cols.pop()
    per_employee_df = pd.DataFrame(index=GDP_df.index, columns=cols)
    per_HW_df = pd.DataFrame(index=GDP_df.index, columns=cols)
    for i in cols:
        per_employee_df[i] = GDP_df[i]/employees_df[i]
        per_HW_df[i] = per_employee_df[i]/HW_df[i]
    return per_employee_df, per_HW_df

GDP_df =  load_df('./data/GDP_per_quarter_2.xlsx') * 1e6
HW_df = load_df('./data/hours_worked.xlsx')
employees_df = load_df('./data/Employees.xlsx') * 1e3
per_employee_df, per_HW_df = create_per_employeer(GDP_df, HW_df, employees_df)

In [44]:
per_HW_df

,2008-Q1,2008-Q2,2008-Q3,2008-Q4,2009-Q1,2009-Q2,2009-Q3,2009-Q4,2010-Q1,2010-Q2,...,2019-Q2,2019-Q3,2019-Q4,2020-Q1,2020-Q2,2020-Q3,2020-Q4,2021-Q1,2021-Q2,2021-Q3
TIME,,,,,,,,,,,,,,,,,,,,,
Belgium,611.402642,650.509000,611.189001,643.449734,609.283943,621.255617,609.988497,665.392445,616.821551,653.559524,...,781.186857,751.422297,826.953821,757.363015,697.283950,740.861798,818.986723,798.488287,832.346996,810.219452
Bulgaria,64.485616,73.585609,83.978307,84.170255,67.164116,78.884587,85.638898,89.906787,70.283027,83.692961,...,132.850213,140.475386,150.054807,120.599117,132.878265,150.262363,158.008789,129.145951,148.563718,169.056203
Czechia,213.788847,237.927883,249.455512,234.787323,200.832967,220.343577,232.028277,237.178025,219.683756,242.016209,...,327.919628,333.933911,343.652461,311.266007,294.832550,324.634480,335.597217,319.635254,358.684483,362.109816
Denmark,678.865532,702.741710,698.890381,719.966763,683.246776,694.388128,699.560334,749.470180,725.845460,758.798584,...,922.540572,899.795253,928.473043,906.720783,895.945101,924.479816,962.315027,906.093079,943.762778,936.824282
Germany (until 1990 former territory of the FRG),533.261691,537.787264,526.458031,525.027097,498.587068,498.165814,516.895246,521.901949,526.844000,530.364765,...,662.946576,670.291155,670.776516,653.168535,593.935393,661.429813,689.269713,671.321564,679.806980,704.338582
Estonia,171.701788,190.377468,182.534316,178.910157,164.867715,176.504979,169.971297,183.658263,175.466804,191.819752,...,330.497382,328.107378,339.227333,302.046534,315.120648,329.468547,347.572388,323.745433,362.060103,380.556094
Ireland,730.837838,712.962459,709.483959,717.768395,729.491893,737.183130,730.276180,725.745522,751.570211,748.128309,...,1195.186922,1296.389764,1293.331757,1306.859698,1236.788105,1436.662633,1338.430432,1476.221373,1412.989267,1531.442622
Greece,450.237773,475.350999,493.613691,494.032784,431.791418,479.375864,484.782423,510.227724,454.466483,467.887041,...,412.272885,439.291495,417.200137,376.636277,352.259744,396.261942,387.377776,397.830785,403.502943,439.779489
Spain,404.288417,428.318029,407.299761,448.923237,417.554579,441.016492,422.911119,459.404170,432.763968,454.549890,...,508.530716,485.840385,519.190295,470.499049,433.278550,470.792687,498.144841,469.709164,492.792130,472.956635
France,568.928419,571.953573,549.212748,573.509524,554.414509,556.772397,541.990617,584.201462,569.643620,578.276966,...,688.967836,676.998156,706.971493,659.278661,605.976591,667.280269,699.233322,692.946415,697.028246,691.564656
Croatia,197.836562,217.139634,229.073234,209.427166,184.781968,206.160226,215.964191,203.881102,194.616149,218.304599,...,243.106443,266.548214,234.594521,218.462993,203.704639,234.821545,225.638743,221.519436,246.533848,284.874983
Italy,614.724780,633.805433,602.236385,651.236052,585.712091,607.700298,600.325440,655.454294,601.425367,636.596891,...,671.429938,668.084421,722.759252,623.790475,581.662123,657.672491,705.569032,666.849443,679.301306,675.457148
Cyprus,375.373878,393.819082,403.736584,384.606702,372.976203,382.752100,382.109254,383.920531,373.786800,381.149371,...,420.976018,426.287693,411.001940,399.597559,358.915704,408.228509,395.208185,392.873987,405.058293,408.451737
Latvia,159.120993,170.061795,172.231411,171.989928,146.122321,159.748742,154.552304,156.902192,147.410630,157.210414,...,258.173151,271.064257,269.688203,236.081991,243.633285,267.159387,280.454684,254.034761,298.092030,319.129539
Lithuania,148.168233,174.694779,179.371166,173.451343,141.996327,161.119072,154.844543,154.340066,152.583747,171.991608,...,267.379856,286.434476,282.068803,247.939757,264.337257,305.109126,293.641543,267.859190,301.535697,328.714777
Luxembourg,1425.268213,1418.096115,1410.207502,1514.375706,1326.741718,1297.571029,1288.201949,1404.458392,1373.416119,1424.507458,...,1557.086808,1568.041358,1719.897542,1566.651317,1550.112857,1634.916399,1780.708904,1665.461930,1697.799449,1729.477452
Hungary,182.780347,205.539395,210.447554,206.027251,158.254542,176.297200,188.118606,208.124210,177.539074,190.770871,...,231.181655,235.967247,254.068693,211.643249,207.286713,227.372228,250.260724,205.514624,246.234896,250.586920
Malta,273.240504,289.057951,304.443337,299.519112,279.399420,291.326538,308.657545,301.185227,305.669555,308.707611,...,422.566958,434.569366,421.012449,391.542878,357.512488,387.826442,393.901844,403.162468,409.106384,431.207378
Netherlands,731.308996,743.776963,710.094035,745.408498,712.456791,717.514201,692.080452,740.771665,730.881398,761.840865,...,932.333140,889.044751,933.476668,903.137467,876.910730,900.257931,948.234116,859.603142,913.162184,889.627631
Austria,537.344956,563.244566,549.679923,574.753142,535.440455,548.677465,546.810112,583.284671,546.040840,568.177707,...,712.706775,706.655983,745.302950,698.560442,659.720954,696.998266,727.433366,689.959372,753.029010,755.286594
Poland,174.078241,185.706827,188.960788,189.265042,145.741132,150.039186,160.263145,184.170916,177.163957,181.744398,...,247.493066,249.741554,285.709455,250.498124,231.450128,254.425512,281.090960,249.998452,259.099249,265.784333
Portugal,288.915623,299.572340,299.832015,308.177791,281.925248,301.167284,303.663268,319.456583,298.666830,308.348251,...,339.595452,339.722737,350.327880,325.916548,300.033281,333.891508,336.533340,317.970739,330.771045,340.152333
Romania,108.910494,133.935238,160.737536,168.514790,94.704981,117.663462,133.237776,155.117627,109.764507,128.937500,...,198.935146,231.653647,256.549252,176.343948,184.285211,228.843662,261.655848,179.604612,213.728526,245.451598
Slovenia,257.308811,288.541549,276.037821,276.982584,256.623259,287.172253,284.205408,284.984547,263.069771,296.676169,...,365.441533,372.766178,371.502333,336.381920,334.561703,366.713148,361.003600,371.495784,398.549971,396.079499
Slovakia,175.446506,194.370648,205.790137,198.497773,182.022552,194.776037,207.181808,206.544136,204.292882,215.886490,...,274.580560,283.520668,278.490405,252.882548,257.889783,290.425934,286.870872,261.454387,286.488709,298.534124
Finland,579.350013,586.306544,570.942422,621.474505,562.710294,566.491187,561.264723,623.490623,577.384773,591.012423,...,744.788131,724.574777,796.554815,746.155982,728.608518,733.526419,814.915430,786.671414,812.148491,813.004471
Sweden,608.561857,636.858029,573.787072,583.715369,517.919531,547.252417,528.523346,594.939396,607.308831,653.385226,...,740.620919,678.035736,765.242311,728.795145,714.300614,708.673839,805.670044,778.456718,799.168382,742.721011
Iceland,593.989478,514.613933,507.275330,290.805414,461.615552,415.282121,410.751546,431.348542,437.515413,456.046143,...,798.772076,857.226053,895.160981,771.201520,708.199880,694.956061,823.084440,803.975261,846.185897,872.915629
Norway,1043.689143,1071.032865,1040.177821,984.583603,886.112164,878.751165,903.906188,1011.719947,1056.627211,1062.434942,...,1086.386142,1027.796453,1114.019032,1028.514227,869.035740,924.295112,1022.242305,1070.114627,1091.587564,1125.324754
Switzerland,NaN,785.331876,790.029909,832.459651,799.153501,804.652910,820.638052,854.089406,860.023250,904.949899,...,1182.727234,1207.948806,1232.905207,1201.968611,1177.466494,1218.527796,1230.993401,1173.572216,1231.652777,1252.826018
United Kingdom,578.550360,535.941815,533.697849,511.446457,472.862822,482.977302,495.846603,485.150796,509.492716,523.737969,...,641.191276,623.100440,671.058875,656.447182,540.209338,587.534188,587.534188,587.534188,587.534188,587.534188
Montenegro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,134.092025,187.166930,151.113116,111.674385,119.298431,166.704526,166.907014,126.225773,162.768228,228.311029
North Macedonia,79.175770,87.241131,86.957738,97.924195,79.331652,83.021390,84.503900,94.732307,84.090386,89.136663,...,109.190670,112.094510,112.600496,95.442041,87.919681,105.174212,113.191432,97.900072,105.237215,111.626174
Serbia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,115.555691,...,127.682025,132.512809,139.872224,126.779011,124.976393,133.479373,141.972163,129.893238,141.112861,142.920756
Turkey,199.186190,190.260278,219.142529,199.761201,172.470307,179.567240,193.487897,192.835178,188.455082,208.528760,...,178.974157,206.722071,214.711128,193.219244,174.751999,195.771708,191.213680,183.968987,184.565999,224.814750
Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Bosnia and Herzegovina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Kosovo (under United Nations Security Council Resolution 1244/99),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [45]:
per_HW_df.reset_index(inplace = True)
per_HW_df

,TIME,2008-Q1,2008-Q2,2008-Q3,2008-Q4,2009-Q1,2009-Q2,2009-Q3,2009-Q4,2010-Q1,...,2019-Q2,2019-Q3,2019-Q4,2020-Q1,2020-Q2,2020-Q3,2020-Q4,2021-Q1,2021-Q2,2021-Q3
0,Belgium,611.402642,650.509000,611.189001,643.449734,609.283943,621.255617,609.988497,665.392445,616.821551,...,781.186857,751.422297,826.953821,757.363015,697.283950,740.861798,818.986723,798.488287,832.346996,810.219452
1,Bulgaria,64.485616,73.585609,83.978307,84.170255,67.164116,78.884587,85.638898,89.906787,70.283027,...,132.850213,140.475386,150.054807,120.599117,132.878265,150.262363,158.008789,129.145951,148.563718,169.056203
2,Czechia,213.788847,237.927883,249.455512,234.787323,200.832967,220.343577,232.028277,237.178025,219.683756,...,327.919628,333.933911,343.652461,311.266007,294.832550,324.634480,335.597217,319.635254,358.684483,362.109816
3,Denmark,678.865532,702.741710,698.890381,719.966763,683.246776,694.388128,699.560334,749.470180,725.845460,...,922.540572,899.795253,928.473043,906.720783,895.945101,924.479816,962.315027,906.093079,943.762778,936.824282
4,Germany (until 1990 former territory of the FRG),533.261691,537.787264,526.458031,525.027097,498.587068,498.165814,516.895246,521.901949,526.844000,...,662.946576,670.291155,670.776516,653.168535,593.935393,661.429813,689.269713,671.321564,679.806980,704.338582
5,Estonia,171.701788,190.377468,182.534316,178.910157,164.867715,176.504979,169.971297,183.658263,175.466804,...,330.497382,328.107378,339.227333,302.046534,315.120648,329.468547,347.572388,323.745433,362.060103,380.556094
6,Ireland,730.837838,712.962459,709.483959,717.768395,729.491893,737.183130,730.276180,725.745522,751.570211,...,1195.186922,1296.389764,1293.331757,1306.859698,1236.788105,1436.662633,1338.430432,1476.221373,1412.989267,1531.442622
7,Greece,450.237773,475.350999,493.613691,494.032784,431.791418,479.375864,484.782423,510.227724,454.466483,...,412.272885,439.291495,417.200137,376.636277,352.259744,396.261942,387.377776,397.830785,403.502943,439.779489
8,Spain,404.288417,428.318029,407.299761,448.923237,417.554579,441.016492,422.911119,459.404170,432.763968,...,508.530716,485.840385,519.190295,470.499049,433.278550,470.792687,498.144841,469.709164,492.792130,472.956635
9,France,568.928419,571.953573,549.212748,573.509524,554.414509,556.772397,541.990617,584.201462,569.643620,...,688.967836,676.998156,706.971493,659.278661,605.976591,667.280269,699.233322,692.946415,697.028246,691.564656
10,Croatia,197.836562,217.139634,229.073234,209.427166,184.781968,206.160226,215.964191,203.881102,194.616149,...,243.106443,266.548214,234.594521,218.462993,203.704639,234.821545,225.638743,221.519436,246.533848,284.874983
11,Italy,614.724780,633.805433,602.236385,651.236052,585.712091,607.700298,600.325440,655.454294,601.425367,...,671.429938,668.084421,722.759252,623.790475,581.662123,657.672491,705.569032,666.849443,679.301306,675.457148
12,Cyprus,375.373878,393.819082,403.736584,384.606702,372.976203,382.752100,382.109254,383.920531,373.786800,...,420.976018,426.287693,411.001940,399.597559,358.915704,408.228509,395.208185,392.873987,405.058293,408.451737
13,Latvia,159.120993,170.061795,172.231411,171.989928,146.122321,159.748742,154.552304,156.902192,147.410630,...,258.173151,271.064257,269.688203,236.081991,243.633285,267.159387,280.454684,254.034761,298.092030,319.129539
14,Lithuania,148.168233,174.694779,179.371166,173.451343,141.996327,161.119072,154.844543,154.340066,152.583747,...,267.379856,286.434476,282.068803,247.939757,264.337257,305.109126,293.641543,267.859190,301.535697,328.714777
15,Luxembourg,1425.268213,1418.096115,1410.207502,1514.375706,1326.741718,1297.571029,1288.201949,1404.458392,1373.416119,...,1557.086808,1568.041358,1719.897542,1566.651317,1550.112857,1634.916399,1780.708904,1665.461930,1697.799449,1729.477452
16,Hungary,182.780347,205.539395,210.447554,206.027251,158.254542,176.297200,188.118606,208.124210,177.539074,...,231.181655,235.967247,254.068693,211.643249,207.286713,227.372228,250.260724,205.514624,246.234896,250.586920
17,Malta,273.240504,289.057951,304.443337,299.519112,279.399420,291.326538,308.657545,301.185227,305.669555,...,422.566958,434.569366,421.012449,391.542878,357.512488,387.826442,393.901844,403.162468,409.106384,431.207378
18,Netherlands,731.308996,743.776963,710.094035,745.408498,712.456791,717.514201,692.080452,740.771665,730.881398,...,932.333140,889.044751,933.476668,903.137467,876.910730,900.257931,948.234116,859.603142,913.162184,889.627631
19,Austria,537.344956,563.244566,549.679923,574.753142,535.440455,548.677465,546.810112,583.284671,546.040840,...,712.706775,706.655983,745.302950,698.560442,659.720954,696.998266,727.433366,689.959372,753.029010,755.286594
20,Poland,174.078241,185.706827,188.960788,189.265042,145.741132,150.039186,160.263145,184.170916,177.163957,...,247.493066,249.741554,285.709455,250.498124,231.450128,254.425512,281.090960,249.998452,259.099249,265.784333
21,Portugal,288.915623,299.572340,299.832015,308.177791,281.925248,301.167284,303.663268,319.456583,298.666830,...,339.595452,339.722737,350.327880,325.916548,300.033281,333.891508,336.533340,317.970739,330.771045,340.152333
22,Romania,108.910494,133.935238,160.737536,168.514790,94.704981,117.663462,133.237776,155.117627,109.764507,...,198.935146,231.653647,256.549252,176.343948,184.285211,228.843662,261.655848,179.604612,213.728526,245.451598
23,Slovenia,257.308811,288.541549,276.037821,276.982584,256.623259,287.172253,284.205408,284.984547,263.069771,...,365.441533,372.766178,371.502333,336.381920,334.561703,366.713148,361.003600,371.495784,398.549971,396.079499
24,Slovakia,175.446506,194.370648,205.790137,198.497773,182.022552,194.776037,207.181808,206.544136,204.292882,...,274.580560,283.520668,278.490405,252.882548,257.889783,290.425934,286.870872,261.454387,286.488709,298.534124
25,Finland,579.350013,586.306544,570.942422,621.474505,562.710294,566.491187,561.264723,623.490623,577.384773,...,744.788131,724.574777,796.554815,746.155982,728.608518,733.526419,814.915430,786.671414,812.148491,813.004471
26,Sweden,608.561857,636.858029,573.787072,583.715369,517.919531,547.252417,528.523346,594.939396,607.308831,...,740.620919,678.035736,765.242311,728.795145,714.300614,708.673839,805.670044,778.456718,799.168382,742.721011
27,Iceland,593.989478,514.613933,507.275330,290.805414,461.615552,415.282121,410.751546,431.348542,437.515413,...,798.772076,857.226053,895.160981,771.201520,708.199880,694.956061,823.084440,803.975261,846.185897,872.915629
28,Norway,1043.689143,1071.032865,1040.177821,984.583603,886.112164,878.751165,903.906188,1011.719947,1056.627211,...,1086.386142,1027.796453,1114.019032,1028.514227,869.035740,924.295112,1022.242305,1070.114627,1091.587564,1125.324754
29,Switzerland,NaN,785.331876,790.029909,832.459651,799.153501,804.652910,820.638052,854.089406,860.023250,...,1182.727234,1207.948806,1232.905207,1201.968611,1177.466494,1218.527796,1230.993401,1173.572216,1231.652777,1252.826018
30,United Kingdom,578.550360,535.941815,533.697849,511.446457,472.862822,482.977302,495.846603,485.150796,509.492716,...,641.191276,623.100440,671.058875,656.447182,540.209338,587.534188,587.534188,587.534188,587.534188,587.534188
31,Montenegro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,134.092025,187.166930,151.113116,111.674385,119.298431,166.704526,166.907014,126.225773,162.768228,228.311029
32,North Macedonia,79.175770,87.241131,86.957738,97.924195,79.331652,83.021390,84.503900,94.732307,84.090386,...,109.190670,112.094510,112.600496,95.442041,87.919681,105.174212,113.191432,97.900072,105.237215,111.626174
33,Serbia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,127.682025,132.512809,139.872224,126.779011,124.976393,133.479373,141.972163,129.893238,141.112861,142.920756
34,Turkey,199.186190,190.260278,219.142529,199.761201,172.470307,179.567240,193.487897,192.835178,188.455082,...,178.974157,206.722071,214.711128,193.219244,174.751999,195.771708,191.213680,183.968987,184.565999,224.814750
35,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Bosnia and Herzegovina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,Kosovo (under United Nations Security Council ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [46]:
hours = per_HW_df.drop(labels = [1,2,3,10,12,16,17,20,22,26,27,28,29,30,31,32,33,34,35,36,37], axis = 0)
hours.reset_index(inplace=True)

In [47]:
unem = pd.read_csv('./data/unem.csv')
unem.fillna(0)
clean = unem[['LOCATION', 'TIME', 'Value']]
df = clean.pivot_table('Value',  ['LOCATION'],'TIME')
df = df.rename({'AUT': 'Austria'})
df = df.rename({'BEL': 'Belgium'})
df = df.rename({'DEU': 'Germany'})
df = df.rename({'ESP': 'Spain'})
df = df.rename({'EST': 'Estonia'})
df = df.rename({'FIN': 'Finland'})
df = df.rename({'FRA': 'France'})
df = df.rename({'GRC': 'Greece'})
df = df.rename({'IRL': 'Ireland'})
df = df.rename({'ITA': 'Italy'})
df = df.rename({'LTU': 'Lithuania'})
df = df.rename({'LUX': 'Luxembourg'})
df = df.rename({'LVA': 'Latvia'})
df = df.rename({'PRT': 'Portugal'})
df = df.rename({'NLD': 'Netherlands'})
df = df.rename({'SVK': 'Slovakia'})
df = df.rename({'SVN': 'Slovenia'})

df.reset_index(inplace=True)
df = df.reindex([1,2,4,8,7,3,6,9,12,10,11,13,0,15,17,16,5])
df.reset_index(inplace=True)
df

TIME,index,LOCATION,2000-Q1,2000-Q2,2000-Q3,2000-Q4,2001-Q1,2001-Q2,2001-Q3,2001-Q4,...,2019-Q3,2019-Q4,2020-Q1,2020-Q2,2020-Q3,2020-Q4,2021-Q1,2021-Q2,2021-Q3,2021-Q4
0,1,Belgium,7.100000,6.800000,6.900000,6.633333,6.066667,6.500000,6.300000,7.400000,...,5.233333,5.300000,5.133333,5.400000,6.400000,6.000000,6.633333,6.366667,6.233333,5.900000
1,2,Germany,8.133333,8.000000,7.900000,7.766667,7.666667,7.666667,7.833333,8.033334,...,3.100000,3.200000,3.500000,3.800000,4.066667,4.066667,3.900000,3.600000,3.366667,3.200000
2,4,Estonia,14.366670,14.133330,14.133330,14.266670,14.100000,13.566670,12.800000,11.666670,...,4.233333,4.333333,5.233333,7.000000,7.633333,7.566667,6.966667,6.633333,5.900000,5.400000
3,8,Ireland,4.800000,4.600000,4.266667,3.900000,3.966667,4.000000,4.366667,4.366667,...,5.000000,4.800000,4.900000,5.100000,7.066667,6.300000,7.400000,6.900000,5.466667,5.233333
4,7,Greece,11.566670,11.466670,11.233330,10.633330,10.500000,10.700000,10.633330,10.866670,...,16.966670,16.633330,15.966670,16.833330,16.866670,16.066670,16.366670,16.033330,13.666670,13.300000
5,3,Spain,12.466670,11.933330,11.800000,11.466670,10.666670,10.500000,10.533330,10.600000,...,14.066670,13.866670,14.133330,15.433330,16.366670,16.266670,15.633330,15.366670,14.700000,13.433330
6,6,France,10.233330,9.700000,9.266666,8.900000,8.700000,8.733334,8.800000,8.800000,...,8.200000,8.133333,7.833333,7.300000,8.866667,8.033334,8.033334,8.166667,7.866667,7.333333
7,9,Italy,10.566670,10.266670,9.966666,9.600000,9.366667,9.133333,9.033334,8.866667,...,9.600000,9.666667,9.000000,8.600000,10.000000,9.766666,10.133330,9.800000,9.100000,9.133333
8,12,Latvia,14.333330,14.366670,14.366670,14.433330,13.800000,13.100000,13.133330,13.933330,...,6.200000,6.066667,7.266667,8.466666,8.600000,8.033334,7.700000,7.766667,7.433333,7.300000
9,10,Lithuania,15.633330,16.500000,16.966670,16.600000,17.733330,17.533330,16.800000,17.500000,...,6.333333,6.600000,7.400000,8.600000,9.266666,8.866667,7.600000,7.500000,6.733333,6.700000
10,11,Luxembourg,2.300000,2.300000,2.233333,2.033333,1.866667,1.866667,1.900000,2.000000,...,5.633333,5.566667,5.966667,7.566667,6.766667,6.266667,6.200000,5.866667,5.266667,4.966667
11,13,Netherlands,3.866667,3.733333,3.566667,3.366667,3.200000,3.100000,3.100000,3.133333,...,4.466667,4.433333,4.066667,4.833333,5.466667,5.066667,4.666667,4.366667,4.133333,3.800000
12,0,Austria,4.233333,3.700000,3.833333,3.766667,3.633333,4.000000,4.100000,4.300000,...,4.833333,4.633333,4.633333,6.933333,6.533333,6.300000,7.066667,6.700000,5.633333,5.266667
13,15,Portugal,5.433333,5.233333,5.300000,5.066667,5.266667,5.400000,5.433333,5.400000,...,6.600000,6.733333,6.600000,6.633333,8.100000,7.233333,6.833333,6.933333,6.433333,6.166667
14,17,Slovenia,6.800000,7.166667,6.800000,6.233333,6.066667,5.933333,6.066667,6.700000,...,4.833333,4.100000,4.266667,5.400000,5.166667,5.200000,5.266667,4.600000,4.500000,4.566667
15,16,Slovakia,18.500000,19.166670,18.966670,18.966670,19.366670,19.533330,19.466670,19.466670,...,5.666667,5.700000,5.966667,6.600000,7.000000,7.033333,7.133333,7.000000,6.600000,6.400000
16,5,Finland,10.166670,9.800000,9.600000,9.400000,9.266666,9.100000,9.066667,9.100000,...,6.766667,6.800000,6.700000,7.766667,8.433333,8.133333,7.966667,8.133333,7.500000,6.900000

In [48]:
hours

,index,TIME,2008-Q1,2008-Q2,2008-Q3,2008-Q4,2009-Q1,2009-Q2,2009-Q3,2009-Q4,...,2019-Q2,2019-Q3,2019-Q4,2020-Q1,2020-Q2,2020-Q3,2020-Q4,2021-Q1,2021-Q2,2021-Q3
0,0,Belgium,611.402642,650.509000,611.189001,643.449734,609.283943,621.255617,609.988497,665.392445,...,781.186857,751.422297,826.953821,757.363015,697.283950,740.861798,818.986723,798.488287,832.346996,810.219452
1,4,Germany (until 1990 former territory of the FRG),533.261691,537.787264,526.458031,525.027097,498.587068,498.165814,516.895246,521.901949,...,662.946576,670.291155,670.776516,653.168535,593.935393,661.429813,689.269713,671.321564,679.806980,704.338582
2,5,Estonia,171.701788,190.377468,182.534316,178.910157,164.867715,176.504979,169.971297,183.658263,...,330.497382,328.107378,339.227333,302.046534,315.120648,329.468547,347.572388,323.745433,362.060103,380.556094
3,6,Ireland,730.837838,712.962459,709.483959,717.768395,729.491893,737.183130,730.276180,725.745522,...,1195.186922,1296.389764,1293.331757,1306.859698,1236.788105,1436.662633,1338.430432,1476.221373,1412.989267,1531.442622
4,7,Greece,450.237773,475.350999,493.613691,494.032784,431.791418,479.375864,484.782423,510.227724,...,412.272885,439.291495,417.200137,376.636277,352.259744,396.261942,387.377776,397.830785,403.502943,439.779489
5,8,Spain,404.288417,428.318029,407.299761,448.923237,417.554579,441.016492,422.911119,459.404170,...,508.530716,485.840385,519.190295,470.499049,433.278550,470.792687,498.144841,469.709164,492.792130,472.956635
6,9,France,568.928419,571.953573,549.212748,573.509524,554.414509,556.772397,541.990617,584.201462,...,688.967836,676.998156,706.971493,659.278661,605.976591,667.280269,699.233322,692.946415,697.028246,691.564656
7,11,Italy,614.724780,633.805433,602.236385,651.236052,585.712091,607.700298,600.325440,655.454294,...,671.429938,668.084421,722.759252,623.790475,581.662123,657.672491,705.569032,666.849443,679.301306,675.457148
8,13,Latvia,159.120993,170.061795,172.231411,171.989928,146.122321,159.748742,154.552304,156.902192,...,258.173151,271.064257,269.688203,236.081991,243.633285,267.159387,280.454684,254.034761,298.092030,319.129539
9,14,Lithuania,148.168233,174.694779,179.371166,173.451343,141.996327,161.119072,154.844543,154.340066,...,267.379856,286.434476,282.068803,247.939757,264.337257,305.109126,293.641543,267.859190,301.535697,328.714777
10,15,Luxembourg,1425.268213,1418.096115,1410.207502,1514.375706,1326.741718,1297.571029,1288.201949,1404.458392,...,1557.086808,1568.041358,1719.897542,1566.651317,1550.112857,1634.916399,1780.708904,1665.461930,1697.799449,1729.477452
11,18,Netherlands,731.308996,743.776963,710.094035,745.408498,712.456791,717.514201,692.080452,740.771665,...,932.333140,889.044751,933.476668,903.137467,876.910730,900.257931,948.234116,859.603142,913.162184,889.627631
12,19,Austria,537.344956,563.244566,549.679923,574.753142,535.440455,548.677465,546.810112,583.284671,...,712.706775,706.655983,745.302950,698.560442,659.720954,696.998266,727.433366,689.959372,753.029010,755.286594
13,21,Portugal,288.915623,299.572340,299.832015,308.177791,281.925248,301.167284,303.663268,319.456583,...,339.595452,339.722737,350.327880,325.916548,300.033281,333.891508,336.533340,317.970739,330.771045,340.152333
14,23,Slovenia,257.308811,288.541549,276.037821,276.982584,256.623259,287.172253,284.205408,284.984547,...,365.441533,372.766178,371.502333,336.381920,334.561703,366.713148,361.003600,371.495784,398.549971,396.079499
15,24,Slovakia,175.446506,194.370648,205.790137,198.497773,182.022552,194.776037,207.181808,206.544136,...,274.580560,283.520668,278.490405,252.882548,257.889783,290.425934,286.870872,261.454387,286.488709,298.534124
16,25,Finland,579.350013,586.306544,570.942422,621.474505,562.710294,566.491187,561.264723,623.490623,...,744.788131,724.574777,796.554815,746.155982,728.608518,733.526419,814.915430,786.671414,812.148491,813.004471

In [50]:
hours.iloc[:,2:59]

,2008-Q1,2008-Q2,2008-Q3,2008-Q4,2009-Q1,2009-Q2,2009-Q3,2009-Q4,2010-Q1,2010-Q2,...,2019-Q2,2019-Q3,2019-Q4,2020-Q1,2020-Q2,2020-Q3,2020-Q4,2021-Q1,2021-Q2,2021-Q3
0,611.402642,650.509000,611.189001,643.449734,609.283943,621.255617,609.988497,665.392445,616.821551,653.559524,...,781.186857,751.422297,826.953821,757.363015,697.283950,740.861798,818.986723,798.488287,832.346996,810.219452
1,533.261691,537.787264,526.458031,525.027097,498.587068,498.165814,516.895246,521.901949,526.844000,530.364765,...,662.946576,670.291155,670.776516,653.168535,593.935393,661.429813,689.269713,671.321564,679.806980,704.338582
2,171.701788,190.377468,182.534316,178.910157,164.867715,176.504979,169.971297,183.658263,175.466804,191.819752,...,330.497382,328.107378,339.227333,302.046534,315.120648,329.468547,347.572388,323.745433,362.060103,380.556094
3,730.837838,712.962459,709.483959,717.768395,729.491893,737.183130,730.276180,725.745522,751.570211,748.128309,...,1195.186922,1296.389764,1293.331757,1306.859698,1236.788105,1436.662633,1338.430432,1476.221373,1412.989267,1531.442622
4,450.237773,475.350999,493.613691,494.032784,431.791418,479.375864,484.782423,510.227724,454.466483,467.887041,...,412.272885,439.291495,417.200137,376.636277,352.259744,396.261942,387.377776,397.830785,403.502943,439.779489
5,404.288417,428.318029,407.299761,448.923237,417.554579,441.016492,422.911119,459.404170,432.763968,454.549890,...,508.530716,485.840385,519.190295,470.499049,433.278550,470.792687,498.144841,469.709164,492.792130,472.956635
6,568.928419,571.953573,549.212748,573.509524,554.414509,556.772397,541.990617,584.201462,569.643620,578.276966,...,688.967836,676.998156,706.971493,659.278661,605.976591,667.280269,699.233322,692.946415,697.028246,691.564656
7,614.724780,633.805433,602.236385,651.236052,585.712091,607.700298,600.325440,655.454294,601.425367,636.596891,...,671.429938,668.084421,722.759252,623.790475,581.662123,657.672491,705.569032,666.849443,679.301306,675.457148
8,159.120993,170.061795,172.231411,171.989928,146.122321,159.748742,154.552304,156.902192,147.410630,157.210414,...,258.173151,271.064257,269.688203,236.081991,243.633285,267.159387,280.454684,254.034761,298.092030,319.129539
9,148.168233,174.694779,179.371166,173.451343,141.996327,161.119072,154.844543,154.340066,152.583747,171.991608,...,267.379856,286.434476,282.068803,247.939757,264.337257,305.109126,293.641543,267.859190,301.535697,328.714777
10,1425.268213,1418.096115,1410.207502,1514.375706,1326.741718,1297.571029,1288.201949,1404.458392,1373.416119,1424.507458,...,1557.086808,1568.041358,1719.897542,1566.651317,1550.112857,1634.916399,1780.708904,1665.461930,1697.799449,1729.477452
11,731.308996,743.776963,710.094035,745.408498,712.456791,717.514201,692.080452,740.771665,730.881398,761.840865,...,932.333140,889.044751,933.476668,903.137467,876.910730,900.257931,948.234116,859.603142,913.162184,889.627631
12,537.344956,563.244566,549.679923,574.753142,535.440455,548.677465,546.810112,583.284671,546.040840,568.177707,...,712.706775,706.655983,745.302950,698.560442,659.720954,696.998266,727.433366,689.959372,753.029010,755.286594
13,288.915623,299.572340,299.832015,308.177791,281.925248,301.167284,303.663268,319.456583,298.666830,308.348251,...,339.595452,339.722737,350.327880,325.916548,300.033281,333.891508,336.533340,317.970739,330.771045,340.152333
14,257.308811,288.541549,276.037821,276.982584,256.623259,287.172253,284.205408,284.984547,263.069771,296.676169,...,365.441533,372.766178,371.502333,336.381920,334.561703,366.713148,361.003600,371.495784,398.549971,396.079499
15,175.446506,194.370648,205.790137,198.497773,182.022552,194.776037,207.181808,206.544136,204.292882,215.886490,...,274.580560,283.520668,278.490405,252.882548,257.889783,290.425934,286.870872,261.454387,286.488709,298.534124
16,579.350013,586.306544,570.942422,621.474505,562.710294,566.491187,561.264723,623.490623,577.384773,591.012423,...,744.788131,724.574777,796.554815,746.155982,728.608518,733.526419,814.915430,786.671414,812.148491,813.004471

In [37]:
df['mean'] = df.iloc[:,33:89].mean(axis=1, skipna = True)
hours['mean'] = hours.iloc[:,2:58].mean(axis=1, skipna = True)

In [38]:

df_new = hours[['mean']].copy()
df_new['unemployment rate'] = df[['mean']].copy()
df_new
corr = df_new.corr()
print(corr)

                       mean  unemployment rate
mean               1.000000          -0.363091
unemployment rate -0.363091           1.000000