In [10]:
#coding utf8
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


sentiment = pd.read_csv('./data/sentiment.csv') 
productivity = pd.read_csv('./data/GDP_per_quarter.csv') 
unem = pd.read_csv('./data/unem.csv')
unem.fillna(0)
productivity.fillna(0)

,Country,2021-Q4,2021-Q3,2021-Q2,2021-Q1,2020-Q4,2020-Q3,2020-Q2,2020-Q1,2019-Q4,...,2002-Q2,2002-Q1,2001-Q4,2001-Q3,2001-Q2,2001-Q1,2000-Q4,2000-Q3,2000-Q2,2000-Q1
0,Slovakia,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.180855e+10,1.953442e+10,2.130274e+10,2.244234e+10,...,1.155564e+10,1.143982e+10,1.140442e+10,1.116490e+10,1.111826e+10,1.100148e+10,1.092408e+10,1.086316e+10,1.079898e+10,1.069456e+10
1,Austria,9.241863e+10,9.377876e+10,9.070556e+10,8.715757e+10,8.750030e+10,8.917405e+10,8.047778e+10,9.086087e+10,9.318910e+10,...,7.206637e+10,7.170129e+10,7.109538e+10,7.069148e+10,7.065559e+10,7.082965e+10,7.107146e+10,6.996467e+10,6.965500e+10,6.922582e+10
2,Belgium,1.136930e+11,1.131120e+11,1.108510e+11,1.089670e+11,1.076290e+11,1.077780e+11,9.633100e+10,1.090200e+11,1.125520e+11,...,8.460400e+10,8.388600e+10,8.317100e+10,8.325400e+10,8.341300e+10,8.339800e+10,8.335100e+10,8.254400e+10,8.216300e+10,8.157600e+10
3,Cyprus,5.722387e+09,5.680197e+09,5.583790e+09,5.495300e+09,5.402400e+09,5.372536e+09,4.926879e+09,5.605236e+09,5.644720e+09,...,3.779115e+09,3.718785e+09,3.682507e+09,3.693130e+09,3.623781e+09,3.554633e+09,3.506329e+09,3.469149e+09,3.574174e+09,3.451010e+09
4,Germany,8.034510e+11,8.062500e+11,7.930100e+11,7.761400e+11,7.894350e+11,7.836100e+11,7.186240e+11,7.984380e+11,8.127750e+11,...,6.487370e+11,6.458620e+11,6.492670e+11,6.500230e+11,6.510830e+11,6.514610e+11,6.386190e+11,6.405860e+11,6.407370e+11,6.355170e+11
5,Estonia,6.569154e+09,6.455124e+09,6.389617e+09,6.238700e+09,6.037598e+09,5.907816e+09,5.701474e+09,6.053237e+09,6.127212e+09,...,3.534022e+09,3.414611e+09,3.390976e+09,3.341946e+09,3.274328e+09,3.270264e+09,3.223752e+09,3.152816e+09,3.114389e+09,3.038302e+09
6,Spain,2.880450e+11,2.823650e+11,2.751290e+11,2.718860e+11,2.737190e+11,2.731110e+11,2.338310e+11,2.839550e+11,3.001360e+11,...,2.329420e+11,2.310590e+11,2.300800e+11,2.284990e+11,2.263890e+11,2.247280e+11,2.223670e+11,2.200990e+11,2.177490e+11,2.150560e+11
7,Finland,5.888300e+10,5.847100e+10,5.789500e+10,5.686400e+10,5.693500e+10,5.641300e+10,5.372100e+10,5.724900e+10,5.740400e+10,...,4.614800e+10,4.569600e+10,4.539900e+10,4.552700e+10,4.524100e+10,4.518700e+10,4.496700e+10,4.449400e+10,4.380800e+10,4.347300e+10
8,France,5.946380e+11,5.904640e+11,5.725200e+11,5.650850e+11,5.641260e+11,5.703250e+11,4.809560e+11,5.557900e+11,5.893200e+11,...,4.754990e+11,4.733170e+11,4.715550e+11,4.714330e+11,4.701620e+11,4.692930e+11,4.667350e+11,4.629730e+11,4.600970e+11,4.555980e+11
9,Greece,4.584950e+10,4.565604e+10,4.476764e+10,4.432106e+10,4.258747e+10,4.097389e+10,3.888867e+10,4.493059e+10,4.583614e+10,...,4.931402e+10,4.823439e+10,4.784349e+10,4.771708e+10,4.695564e+10,4.707973e+10,4.650407e+10,4.585344e+10,4.501243e+10,4.460121e+10
10,Euro area,2.854890e+12,2.847560e+12,2.784780e+12,2.724650e+12,2.728240e+12,2.737040e+12,2.429880e+12,2.749560e+12,2.849970e+12,...,2.318970e+12,2.306470e+12,2.304250e+12,2.301550e+12,2.299280e+12,2.297100e+12,2.273770e+12,2.258740e+12,2.246620e+12,2.226220e+12
11,Ireland,9.870866e+10,1.043020e+11,1.030240e+11,9.847247e+10,8.973704e+10,9.370313e+10,8.532482e+10,8.799766e+10,8.557602e+10,...,3.945551e+10,3.916320e+10,3.808159e+10,3.750901e+10,3.781426e+10,3.718079e+10,3.625790e+10,3.616305e+10,3.557843e+10,3.441913e+10
12,Italy,4.286820e+11,4.262490e+11,4.158820e+11,4.050610e+11,4.036780e+11,4.100990e+11,3.534960e+11,4.045990e+11,4.299440e+11,...,4.236520e+11,4.219260e+11,4.214590e+11,4.222090e+11,4.234150e+11,4.250930e+11,4.222830e+11,4.162720e+11,4.137340e+11,4.103960e+11
13,Lithuania,1.154467e+10,1.141665e+10,1.133518e+10,1.120127e+10,1.101543e+10,1.084672e+10,1.044143e+10,1.109183e+10,1.101126e+10,...,5.727398e+09,5.553462e+09,5.547358e+09,5.418847e+09,5.312136e+09,5.293208e+09,5.168622e+09,5.090859e+09,5.015338e+09,4.964666e+09
14,Luxembourg,1.602294e+10,1.594123e+10,1.586494e+10,1.586010e+10,1.528643e+10,1.520464e+10,1.407860e+10,1.501331e+10,1.518056e+10,...,9.802697e+09,9.633340e+09,9.593224e+09,9.348614e+09,9.216029e+09,9.332280e+09,9.182490e+09,9.128852e+09,8.972510e+09,9.091510e+09
15,Latvia,7.006043e+09,7.011162e+09,6.977314e+09,6.837968e+09,6.793592e+09,6.686103e+09,6.333569e+09,6.814765e+09,6.926659e+09,...,4.043383e+09,3.899953e+09,3.899595e+09,3.775036e+09,3.853664e+09,3.687831e+09,3.605985e+09,3.651407e+09,3.539236e+09,3.546912e+09
16,Malta,3.347345e+09,3.271927e+09,3.166041e+09,3.135257e+09,3.043732e+09,2.902212e+09,2.728447e+09,3.150512e+09,3.303353e+09,...,1.530871e+09,1.530572e+09,1.496564e+09,1.503344e+09,1.475233e+09,1.495686e+09,1.540639e+09,1.506576e+09,1.528148e+09,1.462303e+09
17,Netherlands,1.958590e+11,1.940600e+11,1.900560e+11,1.831740e+11,1.846080e+11,1.846070e+11,1.717180e+11,1.874160e+11,1.905480e+11,...,1.488760e+11,1.483590e+11,1.492700e+11,1.487900e+11,1.485320e+11,1.477840e+11,1.476240e+11,1.457300e+11,1.445370e+11,1.429410e+11
18,Portugal,4.987104e+10,4.909440e+10,4.777122e+10,4.578896e+10,4.713387e+10,4.700456e+10,4.099022e+10,4.836586e+10,5.059960e+10,...,4.489984e+10,4.510914e+10,4.502908e+10,4.440780e+10,4.434290e+10,4.391802e+10,4.405578e+10,4.376283e+10,4.313102e+10,4.336017e+10
19,Slovenia,1.227312e+10,1.164805e+10,1.149317e+10,1.126830e+10,1.110580e+10,1.112624e+10,9.949593e+09,1.098621e+10,1.151627e+10,...,7.696591e+09,7.704116e+09,7.601874e+09,7.528373e+09,7.483864e+09,7.463842e+09,7.370898e+09,7.320786e+09,7.236308e+09,7.135116e+09

In [11]:
#clean the dataset, keeping only the columns you need
clean = unem[['LOCATION', 'TIME', 'Value']]
clean

     LOCATION     TIME     Value
0         AUT  2000-Q1  4.233333
1         AUT  2000-Q2  3.700000
2         AUT  2000-Q3  3.833333
3         AUT  2000-Q4  3.766667
4         AUT  2001-Q1  3.633333
...       ...      ...       ...
1575      LTU  2020-Q4  8.866667
1576      LTU  2021-Q1  7.600000
1577      LTU  2021-Q2  7.500000
1578      LTU  2021-Q3  6.733333
1579      LTU  2021-Q4  6.700000

[1580 rows x 3 columns]

In [12]:
df = clean.pivot_table('Value',  ['LOCATION'],'TIME')
df = df.rename({'AUT': 'Austria'})
df = df.rename({'BEL': 'Belgium'})
df = df.rename({'DEU': 'Germany'})
df = df.rename({'ESP': 'Spain'})
df = df.rename({'EST': 'Estonia'})
df = df.rename({'FIN': 'Finland'})
df = df.rename({'FRA': 'France'})
df = df.rename({'GRC': 'Greece'})
df = df.rename({'IRL': 'Ireland'})
df = df.rename({'ITA': 'Italy'})
df = df.rename({'LTU': 'Lithuania'})
df = df.rename({'LUX': 'Luxembourg'})
df = df.rename({'LVA': 'Latvia'})
df = df.rename({'PRT': 'Portugal'})
df = df.rename({'NLD': 'Netherlands'})
df = df.rename({'SVK': 'Slovakia'})
df = df.rename({'SVN': 'Slovenia'})

df.reset_index(inplace=True)
df

TIME,LOCATION,2000-Q1,2000-Q2,2000-Q3,2000-Q4,2001-Q1,2001-Q2,2001-Q3,2001-Q4,2002-Q1,...,2019-Q3,2019-Q4,2020-Q1,2020-Q2,2020-Q3,2020-Q4,2021-Q1,2021-Q2,2021-Q3,2021-Q4
0,Austria,4.233333,3.700000,3.833333,3.766667,3.633333,4.000000,4.100000,4.300000,4.500000,...,4.833333,4.633333,4.633333,6.933333,6.533333,6.300000,7.066667,6.700000,5.633333,5.266667
1,Belgium,7.100000,6.800000,6.900000,6.633333,6.066667,6.500000,6.300000,7.400000,7.333333,...,5.233333,5.300000,5.133333,5.400000,6.400000,6.000000,6.633333,6.366667,6.233333,5.900000
2,Germany,8.133333,8.000000,7.900000,7.766667,7.666667,7.666667,7.833333,8.033334,8.166667,...,3.100000,3.200000,3.500000,3.800000,4.066667,4.066667,3.900000,3.600000,3.366667,3.200000
3,Spain,12.466670,11.933330,11.800000,11.466670,10.666670,10.500000,10.533330,10.600000,11.266670,...,14.066670,13.866670,14.133330,15.433330,16.366670,16.266670,15.633330,15.366670,14.700000,13.433330
4,Estonia,14.366670,14.133330,14.133330,14.266670,14.100000,13.566670,12.800000,11.666670,11.466670,...,4.233333,4.333333,5.233333,7.000000,7.633333,7.566667,6.966667,6.633333,5.900000,5.400000
5,Finland,10.166670,9.800000,9.600000,9.400000,9.266666,9.100000,9.066667,9.100000,9.100000,...,6.766667,6.800000,6.700000,7.766667,8.433333,8.133333,7.966667,8.133333,7.500000,6.900000
6,France,10.233330,9.700000,9.266666,8.900000,8.700000,8.733334,8.800000,8.800000,8.766666,...,8.200000,8.133333,7.833333,7.300000,8.866667,8.033334,8.033334,8.166667,7.866667,7.333333
7,Greece,11.566670,11.466670,11.233330,10.633330,10.500000,10.700000,10.633330,10.866670,10.700000,...,16.966670,16.633330,15.966670,16.833330,16.866670,16.066670,16.366670,16.033330,13.666670,13.300000
8,Ireland,4.800000,4.600000,4.266667,3.900000,3.966667,4.000000,4.366667,4.366667,4.533333,...,5.000000,4.800000,4.900000,5.100000,7.066667,6.300000,7.400000,6.900000,5.466667,5.233333
9,Italy,10.566670,10.266670,9.966666,9.600000,9.366667,9.133333,9.033334,8.866667,8.533334,...,9.600000,9.666667,9.000000,8.600000,10.000000,9.766666,10.133330,9.800000,9.100000,9.133333
10,Lithuania,15.633330,16.500000,16.966670,16.600000,17.733330,17.533330,16.800000,17.500000,15.933330,...,6.333333,6.600000,7.400000,8.600000,9.266666,8.866667,7.600000,7.500000,6.733333,6.700000
11,Luxembourg,2.300000,2.300000,2.233333,2.033333,1.866667,1.866667,1.900000,2.000000,2.133333,...,5.633333,5.566667,5.966667,7.566667,6.766667,6.266667,6.200000,5.866667,5.266667,4.966667
12,Latvia,14.333330,14.366670,14.366670,14.433330,13.800000,13.100000,13.133330,13.933330,12.600000,...,6.200000,6.066667,7.266667,8.466666,8.600000,8.033334,7.700000,7.766667,7.433333,7.300000
13,Netherlands,3.866667,3.733333,3.566667,3.366667,3.200000,3.100000,3.100000,3.133333,3.300000,...,4.466667,4.433333,4.066667,4.833333,5.466667,5.066667,4.666667,4.366667,4.133333,3.800000
14,OECD,NaN,NaN,NaN,NaN,6.467718,6.530343,6.731309,7.046362,7.141005,...,5.385178,5.352491,5.433552,8.557553,7.706079,6.990134,6.737671,6.461598,5.912374,5.488205
15,Portugal,5.433333,5.233333,5.300000,5.066667,5.266667,5.400000,5.433333,5.400000,5.633333,...,6.600000,6.733333,6.600000,6.633333,8.100000,7.233333,6.833333,6.933333,6.433333,6.166667
16,Slovakia,18.500000,19.166670,18.966670,18.966670,19.366670,19.533330,19.466670,19.466670,19.000000,...,5.666667,5.700000,5.966667,6.600000,7.000000,7.033333,7.133333,7.000000,6.600000,6.400000
17,Slovenia,6.800000,7.166667,6.800000,6.233333,6.066667,5.933333,6.066667,6.700000,6.566667,...,4.833333,4.100000,4.266667,5.400000,5.166667,5.200000,5.266667,4.600000,4.500000,4.566667

In [13]:
df = df.reindex([16, 0, 1, 2, 4, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15, 17, 14])

arr = []
for name in df['LOCATION'].unique(): 
    for n in productivity['Country'].unique():
        if name == n:
            arr.append(name)
        

prod = productivity.drop(labels = [3, 10, 16], axis = 0)

prod.reset_index(inplace=True)
final = df.drop(labels = [14], axis = 0)
#final.reset_index(inplace= True)

In [19]:
final['mean'] = final.iloc[:,1:89].mean(axis=1, skipna = True)
prod['mean'] = prod.iloc[:,2:90].mean(axis=1, skipna = True)
final.reset_index(inplace=True)

TIME,index,LOCATION,2000-Q1,2000-Q2,2000-Q3,2000-Q4,2001-Q1,2001-Q2,2001-Q3,2001-Q4,...,2019-Q4,2020-Q1,2020-Q2,2020-Q3,2020-Q4,2021-Q1,2021-Q2,2021-Q3,2021-Q4,mean
0,16,Slovakia,18.500000,19.166670,18.966670,18.966670,19.366670,19.533330,19.466670,19.466670,...,5.700000,5.966667,6.600000,7.000000,7.033333,7.133333,7.000000,6.600000,6.400000,12.724243
1,0,Austria,4.233333,3.700000,3.833333,3.766667,3.633333,4.000000,4.100000,4.300000,...,4.633333,4.633333,6.933333,6.533333,6.300000,7.066667,6.700000,5.633333,5.266667,5.357197
2,1,Belgium,7.100000,6.800000,6.900000,6.633333,6.066667,6.500000,6.300000,7.400000,...,5.300000,5.133333,5.400000,6.400000,6.000000,6.633333,6.366667,6.233333,5.900000,7.473485
3,2,Germany,8.133333,8.000000,7.900000,7.766667,7.666667,7.666667,7.833333,8.033334,...,3.200000,3.500000,3.800000,4.066667,4.066667,3.900000,3.600000,3.366667,3.200000,6.543561
4,4,Estonia,14.366670,14.133330,14.133330,14.266670,14.100000,13.566670,12.800000,11.666670,...,4.333333,5.233333,7.000000,7.633333,7.566667,6.966667,6.633333,5.900000,5.400000,8.781061
5,3,Spain,12.466670,11.933330,11.800000,11.466670,10.666670,10.500000,10.533330,10.600000,...,13.866670,14.133330,15.433330,16.366670,16.266670,15.633330,15.366670,14.700000,13.433330,15.759469
6,5,Finland,10.166670,9.800000,9.600000,9.400000,9.266666,9.100000,9.066667,9.100000,...,6.800000,6.700000,7.766667,8.433333,8.133333,7.966667,8.133333,7.500000,6.900000,8.250000
7,6,France,10.233330,9.700000,9.266666,8.900000,8.700000,8.733334,8.800000,8.800000,...,8.133333,7.833333,7.300000,8.866667,8.033334,8.033334,8.166667,7.866667,7.333333,9.024621
8,7,Greece,11.566670,11.466670,11.233330,10.633330,10.500000,10.700000,10.633330,10.866670,...,16.633330,15.966670,16.833330,16.866670,16.066670,16.366670,16.033330,13.666670,13.300000,15.660984
9,8,Ireland,4.800000,4.600000,4.266667,3.900000,3.966667,4.000000,4.366667,4.366667,...,4.800000,4.900000,5.100000,7.066667,6.300000,7.400000,6.900000,5.466667,5.233333,7.989773
10,9,Italy,10.566670,10.266670,9.966666,9.600000,9.366667,9.133333,9.033334,8.866667,...,9.666667,9.000000,8.600000,10.000000,9.766666,10.133330,9.800000,9.100000,9.133333,9.423485
11,10,Lithuania,15.633330,16.500000,16.966670,16.600000,17.733330,17.533330,16.800000,17.500000,...,6.600000,7.400000,8.600000,9.266666,8.866667,7.600000,7.500000,6.733333,6.700000,10.470833
12,11,Luxembourg,2.300000,2.300000,2.233333,2.033333,1.866667,1.866667,1.900000,2.000000,...,5.566667,5.966667,7.566667,6.766667,6.266667,6.200000,5.866667,5.266667,4.966667,4.857576
13,12,Latvia,14.333330,14.366670,14.366670,14.433330,13.800000,13.100000,13.133330,13.933330,...,6.066667,7.266667,8.466666,8.600000,8.033334,7.700000,7.766667,7.433333,7.300000,11.049621
14,13,Netherlands,3.866667,3.733333,3.566667,3.366667,3.200000,3.100000,3.100000,3.133333,...,4.433333,4.066667,4.833333,5.466667,5.066667,4.666667,4.366667,4.133333,3.800000,5.746212
15,15,Portugal,5.433333,5.233333,5.300000,5.066667,5.266667,5.400000,5.433333,5.400000,...,6.733333,6.600000,6.633333,8.100000,7.233333,6.833333,6.933333,6.433333,6.166667,9.881439
16,17,Slovenia,6.800000,7.166667,6.800000,6.233333,6.066667,5.933333,6.066667,6.700000,...,4.100000,4.266667,5.400000,5.166667,5.200000,5.266667,4.600000,4.500000,4.566667,6.700379

In [21]:
prod

,index,Country,2021-Q4,2021-Q3,2021-Q2,2021-Q1,2020-Q4,2020-Q3,2020-Q2,2020-Q1,...,2002-Q1,2001-Q4,2001-Q3,2001-Q2,2001-Q1,2000-Q4,2000-Q3,2000-Q2,2000-Q1,mean
0,0,Slovakia,NaN,NaN,NaN,NaN,NaN,2.180855e+10,1.953442e+10,2.130274e+10,...,1.143982e+10,1.140442e+10,1.116490e+10,1.111826e+10,1.100148e+10,1.092408e+10,1.086316e+10,1.079898e+10,1.069456e+10,1.692507e+10
1,1,Austria,9.241863e+10,9.377876e+10,9.070556e+10,8.715757e+10,8.750030e+10,8.917405e+10,8.047778e+10,9.086087e+10,...,7.170129e+10,7.109538e+10,7.069148e+10,7.065559e+10,7.082965e+10,7.107146e+10,6.996467e+10,6.965500e+10,6.922582e+10,8.216496e+10
2,2,Belgium,1.136930e+11,1.131120e+11,1.108510e+11,1.089670e+11,1.076290e+11,1.077780e+11,9.633100e+10,1.090200e+11,...,8.388600e+10,8.317100e+10,8.325400e+10,8.341300e+10,8.339800e+10,8.335100e+10,8.254400e+10,8.216300e+10,8.157600e+10,9.776245e+10
3,4,Germany,8.034510e+11,8.062500e+11,7.930100e+11,7.761400e+11,7.894350e+11,7.836100e+11,7.186240e+11,7.984380e+11,...,6.458620e+11,6.492670e+11,6.500230e+11,6.510830e+11,6.514610e+11,6.386190e+11,6.405860e+11,6.407370e+11,6.355170e+11,7.169123e+11
4,5,Estonia,6.569154e+09,6.455124e+09,6.389617e+09,6.238700e+09,6.037598e+09,5.907816e+09,5.701474e+09,6.053237e+09,...,3.414611e+09,3.390976e+09,3.341946e+09,3.274328e+09,3.270264e+09,3.223752e+09,3.152816e+09,3.114389e+09,3.038302e+09,4.821127e+09
5,6,Spain,2.880450e+11,2.823650e+11,2.751290e+11,2.718860e+11,2.737190e+11,2.731110e+11,2.338310e+11,2.839550e+11,...,2.310590e+11,2.300800e+11,2.284990e+11,2.263890e+11,2.247280e+11,2.223670e+11,2.200990e+11,2.177490e+11,2.150560e+11,2.637005e+11
6,7,Finland,5.888300e+10,5.847100e+10,5.789500e+10,5.686400e+10,5.693500e+10,5.641300e+10,5.372100e+10,5.724900e+10,...,4.569600e+10,4.539900e+10,4.552700e+10,4.524100e+10,4.518700e+10,4.496700e+10,4.449400e+10,4.380800e+10,4.347300e+10,5.238119e+10
7,8,France,5.946380e+11,5.904640e+11,5.725200e+11,5.650850e+11,5.641260e+11,5.703250e+11,4.809560e+11,5.557900e+11,...,4.733170e+11,4.715550e+11,4.714330e+11,4.701620e+11,4.692930e+11,4.667350e+11,4.629730e+11,4.600970e+11,4.555980e+11,5.272644e+11
8,9,Greece,4.584950e+10,4.565604e+10,4.476764e+10,4.432106e+10,4.258747e+10,4.097389e+10,3.888867e+10,4.493059e+10,...,4.823439e+10,4.784349e+10,4.771708e+10,4.695564e+10,4.707973e+10,4.650407e+10,4.585344e+10,4.501243e+10,4.460121e+10,4.934598e+10
9,11,Ireland,9.870866e+10,1.043020e+11,1.030240e+11,9.847247e+10,8.973704e+10,9.370313e+10,8.532482e+10,8.799766e+10,...,3.916320e+10,3.808159e+10,3.750901e+10,3.781426e+10,3.718079e+10,3.625790e+10,3.616305e+10,3.557843e+10,3.441913e+10,5.658754e+10
10,12,Italy,4.286820e+11,4.262490e+11,4.158820e+11,4.050610e+11,4.036780e+11,4.100990e+11,3.534960e+11,4.045990e+11,...,4.219260e+11,4.214590e+11,4.222090e+11,4.234150e+11,4.250930e+11,4.222830e+11,4.162720e+11,4.137340e+11,4.103960e+11,4.246378e+11
11,13,Lithuania,1.154467e+10,1.141665e+10,1.133518e+10,1.120127e+10,1.101543e+10,1.084672e+10,1.044143e+10,1.109183e+10,...,5.553462e+09,5.547358e+09,5.418847e+09,5.312136e+09,5.293208e+09,5.168622e+09,5.090859e+09,5.015338e+09,4.964666e+09,8.392801e+09
12,14,Luxembourg,1.602294e+10,1.594123e+10,1.586494e+10,1.586010e+10,1.528643e+10,1.520464e+10,1.407860e+10,1.501331e+10,...,9.633340e+09,9.593224e+09,9.348614e+09,9.216029e+09,9.332280e+09,9.182490e+09,9.128852e+09,8.972510e+09,9.091510e+09,1.237132e+10
13,15,Latvia,7.006043e+09,7.011162e+09,6.977314e+09,6.837968e+09,6.793592e+09,6.686103e+09,6.333569e+09,6.814765e+09,...,3.899953e+09,3.899595e+09,3.775036e+09,3.853664e+09,3.687831e+09,3.605985e+09,3.651407e+09,3.539236e+09,3.546912e+09,5.651971e+09
14,17,Netherlands,1.958590e+11,1.940600e+11,1.900560e+11,1.831740e+11,1.846080e+11,1.846070e+11,1.717180e+11,1.874160e+11,...,1.483590e+11,1.492700e+11,1.487900e+11,1.485320e+11,1.477840e+11,1.476240e+11,1.457300e+11,1.445370e+11,1.429410e+11,1.671088e+11
15,18,Portugal,4.987104e+10,4.909440e+10,4.777122e+10,4.578896e+10,4.713387e+10,4.700456e+10,4.099022e+10,4.836586e+10,...,4.510914e+10,4.502908e+10,4.440780e+10,4.434290e+10,4.391802e+10,4.405578e+10,4.376283e+10,4.313102e+10,4.336017e+10,4.596198e+10
16,19,Slovenia,1.227312e+10,1.164805e+10,1.149317e+10,1.126830e+10,1.110580e+10,1.112624e+10,9.949593e+09,1.098621e+10,...,7.704116e+09,7.601874e+09,7.528373e+09,7.483864e+09,7.463842e+09,7.370898e+09,7.320786e+09,7.236308e+09,7.135116e+09,9.457837e+09

In [23]:
df_new = arr
df_new = prod[['mean']].copy()
df_new['unemployment rate'] = final[['mean']].copy()
df_new
corr = df_new.corr()
print(corr)

                       mean  unemployment rate
mean               1.000000          -0.081756
unemployment rate -0.081756           1.000000

In [24]:
df_new

            mean  unemployment rate
0   1.692507e+10          12.724243
1   8.216496e+10           5.357197
2   9.776245e+10           7.473485
3   7.169123e+11           6.543561
4   4.821127e+09           8.781061
5   2.637005e+11          15.759469
6   5.238119e+10           8.250000
7   5.272644e+11           9.024621
8   4.934598e+10          15.660984
9   5.658754e+10           7.989773
10  4.246378e+11           9.423485
11  8.392801e+09          10.470833
12  1.237132e+10           4.857576
13  5.651971e+09          11.049621
14  1.671088e+11           5.746212
15  4.596198e+10           9.881439
16  9.457837e+09           6.700379