In [262]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import pearsonr

In [263]:
depage = pd.read_csv('../data/depression_by_age.csv') 
prod = pd.read_csv('../data/productivity.csv')
prod = prod.drop(['Unnamed: 18'],axis=1)
prod = prod.drop(['2020'],axis=1)
depage = depage.drop(['Prevalence - Depressive disorders - Sex: Both - Age: 10 to 14 (Percent)'],axis=1)
depage = depage.drop(['Prevalence - Depressive disorders - Sex: Both - Age: All Ages (Percent)'],axis=1)
depage = depage.drop(['Prevalence - Depressive disorders - Sex: Both - Age: 70+ years (Percent)'],axis=1)
depage = depage.drop(['Prevalence - Depressive disorders - Sex: Both - Age: Age-standardized (Percent)'],axis=1)
depage = depage.drop(['Prevalence - Depressive disorders - Sex: Both - Age: 15-49 years (Percent)'],axis=1)
depres_age = pd.DataFrame(depage)
productivity = pd.DataFrame(prod)
depres_age['Age:15-69_depression_average']=depres_age.iloc[:,3:7].mean(axis=1,skipna=True)
depression_age= depres_age.pivot_table('Age:15-69_depression_average', ['Entity', 'Code'], 'Year')
#depres_age= depres_age.pivot_table('Prevalence - Depressive disorders - Sex: Both - Age: Age-standardized (Percent)', ['Entity', 'Code'], 'Year')
#arr = df2['Country'].unique()

#df3 = df1.set_index(['Entity','Code','Prevalence - Depressive disorders - Sex: Both - Age: Age-standardized (Percent)','Year'],drop=True).unstack('Year')
#df3

depression_age

,Year,1990.0,1991.0,1992.0,1993.0,1994.0,1995.0,1996.0,1997.0,1998.0,1999.0,...,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0
Entity,Code,,,,,,,,,,,,,,,,,,,,,
Afghanistan,AFG,6.198882,6.161740,6.119339,6.097139,6.084386,6.073306,6.067813,6.069246,6.081514,6.096978,...,6.036614,6.040745,6.048474,6.057485,6.067506,6.075849,6.060750,6.044674,6.051732,6.061327
Albania,ALB,2.827356,2.841011,2.851627,2.865324,2.875203,2.887080,2.900808,2.910143,2.917918,2.942517,...,2.903065,2.896010,2.888145,2.883225,2.881161,2.875876,2.874310,2.875697,2.876705,2.877968
Algeria,DZA,5.182745,5.164669,5.142744,5.127728,5.118733,5.109131,5.097926,5.090288,5.080537,5.076984,...,4.904332,4.909119,4.921024,4.938951,4.953826,4.961613,4.952129,4.942297,4.972747,5.034503
American Samoa,ASM,3.045105,3.028265,3.015720,3.004950,2.991227,2.984199,2.976842,2.970025,2.963053,2.956790,...,2.889622,2.892981,2.896047,2.897277,2.903852,2.904614,2.901372,2.904861,2.918846,2.948750
Andorra,AND,4.681111,4.668131,4.667106,4.669414,4.665271,4.667587,4.668592,4.660428,4.647929,4.634195,...,4.488511,4.503198,4.500699,4.509241,4.515612,4.513374,4.509022,4.505147,4.526594,4.573584
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Vietnam,VNM,2.704831,2.689910,2.674843,2.659739,2.645194,2.636574,2.625419,2.615226,2.607565,2.600632,...,2.488253,2.483999,2.485708,2.490346,2.495079,2.498696,2.497627,2.496593,2.498086,2.501697
World,OWID_WRL,3.973785,4.026027,4.068308,4.099613,4.119244,4.125911,4.117388,4.097233,4.073039,4.052640,...,3.782591,3.783940,3.791467,3.801586,3.812194,3.820323,3.823534,3.827668,3.838462,3.854556
Yemen,YEM,6.195608,6.214682,6.229987,6.237784,6.246192,6.243986,6.241783,6.239616,6.232503,6.227713,...,6.092769,6.088729,6.085950,6.087336,6.084158,6.085461,6.080035,6.067922,6.066857,6.070047
Zambia,ZMB,4.458934,4.464116,4.471771,4.473090,4.475309,4.477256,4.482442,4.493147,4.508604,4.515941,...,4.391705,4.381862,4.376189,4.374582,4.377822,4.382805,4.388809,4.397031,4.404267,4.412587
Zimbabwe,ZWE,3.386574,3.388321,3.381123,3.374863,3.367325,3.359631,3.341632,3.313227,3.283592,3.257715,...,3.265066,3.280862,3.320219,3.366189,3.406573,3.428625,3.432893,3.438304,3.449047,3.460582

In [264]:
depres_age=depres_age.drop(['Prevalence - Depressive disorders - Sex: Both - Age: 20 to 24 (Percent)'],axis=1)
depres_age=depres_age.drop(['Prevalence - Depressive disorders - Sex: Both - Age: 30 to 34 (Percent)'],axis=1)
depres_age=depres_age.drop(['Prevalence - Depressive disorders - Sex: Both - Age: 15 to 19 (Percent)'],axis=1)
depres_age=depres_age.drop(['Prevalence - Depressive disorders - Sex: Both - Age: 25 to 29 (Percent)'],axis=1)
depres_age=depres_age.drop(['Prevalence - Depressive disorders - Sex: Both - Age: 50-69 years (Percent)'],axis=1)

In [ ]:
arr = depres_age['Entity'].unique()
arr1=productivity['Country'].unique()


arr2 = []
for name in arr:
    for name2 in arr1:
        if(name == name2):
            arr2.append(name2)

In [258]:
productivity.drop(index = [36],inplace=True)

productivity.reset_index(inplace=True)

In [259]:
depression_age = depression_age.loc[arr2]
depression_age = depression_age.iloc[:,15:]
depression_age

,Year,2005.0,2006.0,2007.0,2008.0,2009.0,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0
Entity,Code,,,,,,,,,,,,,,,
Austria,AUT,4.083863,4.037775,3.984647,3.932948,3.894398,3.874706,3.873943,3.884459,3.893957,3.901112,3.902966,3.903100,3.904541,3.909877,3.919968
Belgium,BEL,4.266715,4.319224,4.391753,4.470518,4.529200,4.556212,4.539968,4.505157,4.461023,4.418953,4.392940,4.381039,4.373711,4.381408,4.395594
Bulgaria,BGR,3.028226,2.995716,2.962396,2.931426,2.908188,2.891782,2.881588,2.871204,2.864382,2.863722,2.864399,2.868763,2.877577,2.884754,2.896611
Croatia,HRV,3.402938,3.364246,3.324635,3.289038,3.261386,3.247667,3.238956,3.234906,3.233876,3.231096,3.228554,3.221578,3.219657,3.228227,3.241465
Czech Republic,CZE,3.379736,3.362300,3.344504,3.324768,NaN,3.289528,3.270087,3.247658,3.226062,3.207616,3.197970,3.203591,3.209958,3.213254,3.213693
Denmark,DNK,4.231100,4.187147,4.146883,4.109055,4.084853,4.071869,4.067397,4.072525,4.078029,4.082927,4.083364,4.067379,4.056408,4.068515,4.097514
Finland,FIN,6.240899,6.219611,6.213740,6.216123,6.213358,6.196769,6.141646,6.046789,5.936785,5.845964,5.800599,5.779931,5.759037,5.772166,5.793236
Germany,DEU,4.645292,4.646698,4.638559,4.634948,4.626955,4.622184,4.620408,4.629116,4.628302,4.631207,4.619566,4.548680,4.432185,4.322971,4.201171
Greece,GRC,6.820104,6.808507,6.800087,6.787959,6.777206,6.763624,6.675071,6.494265,6.281567,6.094899,6.002791,5.988131,5.990507,6.029512,6.113405
Hungary,HUN,3.174240,3.142636,3.109443,3.076051,3.046301,3.019514,2.995158,2.965900,2.940505,2.919068,2.909793,2.913987,2.922631,2.924902,2.929328
Iceland,ISL,3.805978,3.770405,3.731196,3.693999,3.670174,3.663785,3.671726,3.684023,3.697834,3.708302,3.715798,3.716855,3.713953,3.732930,3.768624
Ireland,IRL,5.246053,5.246558,5.244699,5.243573,5.240653,5.235530,5.224838,5.201349,5.182215,5.173887,5.187205,5.465402,5.725124,5.726337,5.688510
Italy,ITA,4.622384,4.537320,4.406973,4.267409,4.156614,4.111459,4.126622,4.163634,4.209709,4.247901,4.267986,4.264565,4.263645,4.297771,4.368157
Latvia,LVA,4.136853,4.096461,4.028641,3.953395,3.887468,3.854642,3.844397,3.838568,3.832327,3.828546,3.826320,3.829468,3.838283,3.844814,3.847041
Lithuania,LTU,4.541675,4.500500,4.446829,4.393624,4.344092,4.305447,4.283420,4.257183,4.237614,4.225879,4.213886,4.220244,4.220238,4.217820,4.206985
Norway,NOR,4.238246,4.224115,4.186780,4.142266,4.107887,4.096224,4.111339,4.141127,4.183517,4.234894,4.294734,4.483341,4.640723,4.614963,4.505389
Serbia,SRB,3.097021,3.076980,3.054586,3.033586,3.015336,3.003574,2.995412,2.987027,2.984825,2.982141,2.978439,2.997032,3.020334,3.026423,3.033663
Slovak Republic,SVK,2.862998,2.850568,2.835682,2.818539,2.806354,2.799331,2.812068,2.834584,2.870865,2.899192,2.913651,2.918552,2.924070,2.928577,2.935341
Slovenia,SVN,3.857456,3.799354,3.727869,3.654411,3.586759,3.538172,3.501906,3.464011,3.434307,3.413914,3.403638,3.401735,3.405300,3.409315,3.418644

In [260]:
depression_age['Age:15-69_depression_avg']=depression_age.iloc[:,0:14].mean(axis=1,skipna=True)
depression_age.reset_index(inplace=True)

In [261]:
productivity = productivity[productivity['Country'].notna()]

a=[]
for i in range(0,61):
    if i%2 != 0:
        a.append(i)

productivity = productivity.drop(a)
productivity.reset_index(inplace = True)

productivity.drop(index = [6,8,17,18,19,21,22,23,24,28,29,30,31],inplace=True)

Index(['level_0', 'index', 'unit,na_item,geo\time', 'Country', '2005', '2006',
       '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015',
       '2016', '2017', '2018', '2019'],
      dtype='object')

In [250]:
productivity['Average_Productivity']=productivity.iloc[:,2:20].mean(axis=1,skipna=True)
productivity.drop(['level_0','index'],axis=1)

productivity.reset_index(inplace = True)

/var/folders/2k/j21zjx350njdf7pt9pvz2js40000gn/T/ipykernel_76350/2547592790.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  productivity['Average_Productivity']=productivity.iloc[:,2:20].mean(axis=1,skipna=True)

ValueError: cannot insert level_0, already exists

In [251]:
depression_age

Year,Entity,Code,2005.0,2006.0,2007.0,2008.0,2009.0,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,Age:15-69_depression_avg
0,Austria,AUT,4.083863,4.037775,3.984647,3.932948,3.894398,3.874706,3.873943,3.884459,3.893957,3.901112,3.902966,3.903100,3.904541,3.909877,3.919968,3.927306
1,Belgium,BEL,4.266715,4.319224,4.391753,4.470518,4.529200,4.556212,4.539968,4.505157,4.461023,4.418953,4.392940,4.381039,4.373711,4.381408,4.395594,4.427702
2,Bulgaria,BGR,3.028226,2.995716,2.962396,2.931426,2.908188,2.891782,2.881588,2.871204,2.864382,2.863722,2.864399,2.868763,2.877577,2.884754,2.896611,2.906723
3,Croatia,HRV,3.402938,3.364246,3.324635,3.289038,3.261386,3.247667,3.238956,3.234906,3.233876,3.231096,3.228554,3.221578,3.219657,3.228227,3.241465,3.266197
4,Czech Republic,CZE,3.379736,3.362300,3.344504,3.324768,NaN,3.289528,3.270087,3.247658,3.226062,3.207616,3.197970,3.203591,3.209958,3.213254,3.213693,3.267464
5,Denmark,DNK,4.231100,4.187147,4.146883,4.109055,4.084853,4.071869,4.067397,4.072525,4.078029,4.082927,4.083364,4.067379,4.056408,4.068515,4.097514,4.100532
6,Finland,FIN,6.240899,6.219611,6.213740,6.216123,6.213358,6.196769,6.141646,6.046789,5.936785,5.845964,5.800599,5.779931,5.759037,5.772166,5.793236,6.027387
7,Germany,DEU,4.645292,4.646698,4.638559,4.634948,4.626955,4.622184,4.620408,4.629116,4.628302,4.631207,4.619566,4.548680,4.432185,4.322971,4.201171,4.589076
8,Greece,GRC,6.820104,6.808507,6.800087,6.787959,6.777206,6.763624,6.675071,6.494265,6.281567,6.094899,6.002791,5.988131,5.990507,6.029512,6.113405,6.451016
9,Hungary,HUN,3.174240,3.142636,3.109443,3.076051,3.046301,3.019514,2.995158,2.965900,2.940505,2.919068,2.909793,2.913987,2.922631,2.924902,2.929328,3.004295
10,Iceland,ISL,3.805978,3.770405,3.731196,3.693999,3.670174,3.663785,3.671726,3.684023,3.697834,3.708302,3.715798,3.716855,3.713953,3.732930,3.768624,3.712640
11,Ireland,IRL,5.246053,5.246558,5.244699,5.243573,5.240653,5.235530,5.224838,5.201349,5.182215,5.173887,5.187205,5.465402,5.725124,5.726337,5.688510,5.310245
12,Italy,ITA,4.622384,4.537320,4.406973,4.267409,4.156614,4.111459,4.126622,4.163634,4.209709,4.247901,4.267986,4.264565,4.263645,4.297771,4.368157,4.281714
13,Latvia,LVA,4.136853,4.096461,4.028641,3.953395,3.887468,3.854642,3.844397,3.838568,3.832327,3.828546,3.826320,3.829468,3.838283,3.844814,3.847041,3.902870
14,Lithuania,LTU,4.541675,4.500500,4.446829,4.393624,4.344092,4.305447,4.283420,4.257183,4.237614,4.225879,4.213886,4.220244,4.220238,4.217820,4.206985,4.314889
15,Norway,NOR,4.238246,4.224115,4.186780,4.142266,4.107887,4.096224,4.111339,4.141127,4.183517,4.234894,4.294734,4.483341,4.640723,4.614963,4.505389,4.264297
16,Serbia,SRB,3.097021,3.076980,3.054586,3.033586,3.015336,3.003574,2.995412,2.987027,2.984825,2.982141,2.978439,2.997032,3.020334,3.026423,3.033663,3.018051
17,Slovak Republic,SVK,2.862998,2.850568,2.835682,2.818539,2.806354,2.799331,2.812068,2.834584,2.870865,2.899192,2.913651,2.918552,2.924070,2.928577,2.935341,2.862502
18,Slovenia,SVN,3.857456,3.799354,3.727869,3.654411,3.586759,3.538172,3.501906,3.464011,3.434307,3.413914,3.403638,3.401735,3.405300,3.409315,3.418644,3.542725

In [252]:
correl_signif = pearsonr(productivity['Average_Productivity'], depression_age['Age:15-69_depression_avg'])
correl = correl_signif[0]
correl

ValueError: array must not contain infs or NaNs

In [218]:
import matplotlib.pyplot as plt

x=productivity.loc[:,'Average_Productivity'].values
y=depression_age.loc[:,'Age:15-69_depression_avg'].values

x = x.reshape(len(productivity), 1)
y = y.reshape(len(depression_age), 1)

from sklearn.linear_model import LinearRegression

regr = LinearRegression()
regr.fit(x, y)
print(regr.score(x, y))


fig, ax = plt.subplots(dpi=100, figsize=(6, 4))
fig.patch.set_facecolor('white')
ax.scatter(x, y,  color='black', label='data')
ax.plot(x, regr.predict(x), color='blue', linewidth=3, label='regression')

ax.set_xlabel('Productivity', fontsize=10)
ax.set_ylabel('Depression', fontsize=10)

ax.legend()
plt.show()

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').