In [46]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
productivity = pd.read_csv('./data/productivity.csv') 
prod = productivity[['Country']]
#df = prod.pivot_table('OBS_VALUE',['geo'],'TIME_PERIOD' )
productivity

,"unit,na_item,geo\time",Country,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,Unnamed: 18
0,"PC_EU27_2020_MPPS_CP,NLPR_HW,AT",Austria,117.5,117.8,116.8,116.3,117.5,115.6,115.1,118.0,117.9,118.1,119.7,119.5,117.5,117.8,115.9,117.4,NaN
1,"PC_EU27_2020_MPPS_CP,NLPR_PER,AT",Austria,122.2,121.3,119.5,118.5,118.3,115.7,115.6,118.1,117.4,117.0,117.4,117.8,115.8,116.5,115.5,114.5,NaN
2,"PC_EU27_2020_MPPS_CP,NLPR_HW,BE",Belgium,142.8,139.9,138.0,136.2,136.8,138,134.0,135.2,134.7,136.1,136.8,136.5,134.0,133.5,133.5,137.9,NaN
3,"PC_EU27_2020_MPPS_CP,NLPR_PER,BE",Belgium,133.6,132.1,130.4,127.9,128.7,130.4,128.0,130.2,130.3,131.5,131.7,130.9,129.6,129.3,129.5,129.0,NaN
4,"PC_EU27_2020_MPPS_CP,NLPR_HW,BG",Bulgaria,37.6,37.5,38.8,39.5,40.1,41.9,42.9,44.1,42.9,44.1,44.5,45.8,45.9,47.2,48.6,48.8,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,"PC_EU27_2020_MPPS_CP,NLPR_HW,EU28",NaN,101.7,101.6,101.3,101.3,100.9,101,100.6,100.5,100.3,100.2,100.3,99.9,99.8,99.6,99.6,NaN,NaN
67,"PC_EU27_2020_MPPS_CP,NLPR_PER,EA",NaN,112.4,112.2,111.5,110.7,109.8,108.8,108.2,108.0,108.0,107.8,107.2,107.1,106.8,106.3,105.7,105.0,NaN
68,"PC_EU27_2020_MPPS_CP,NLPR_PER,EA19",NaN,110.4,110.3,109.9,109.3,108.9,108.1,107.6,107.4,107.5,107.5,107.2,107.1,106.8,106.3,105.7,105.0,NaN
69,"PC_EU27_2020_MPPS_CP,NLPR_PER,EU27_2020",NaN,100.0,100.0,100.0,100.0,100,100,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,NaN
70,"PC_EU27_2020_MPPS_CP,NLPR_PER,EU28",NaN,101.6,101.5,101.1,101.0,100.7,100.7,100.4,100.5,100.5,100.5,100.5,100.2,100.1,99.9,100.0,NaN,NaN

In [47]:

prod = pd.read_csv('./data/productivity_new.csv') 
prod = prod[['geo', 'TIME_PERIOD','OBS_VALUE']]
df_productivity = prod.pivot_table('OBS_VALUE',['geo'],'TIME_PERIOD' )
df_productivity
df_productivity['Average Productivity'] = df_productivity.iloc[:,:16].mean(axis=1, skipna= True)
df_productivity

TIME_PERIOD,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,Average Productivity
geo,,,,,,,,,,,,,,,,,
AT,117.5,117.8,116.8,116.3,117.5,115.6,115.1,118.0,117.9,118.1,119.7,119.5,117.5,117.8,115.9,117.4,117.400000
BE,142.8,139.9,138.0,136.2,136.8,138.0,134.0,135.2,134.7,136.1,136.8,136.5,134.0,133.5,133.5,137.8,136.487500
BG,37.6,37.5,38.8,39.5,40.1,41.9,42.9,44.1,42.9,44.1,44.5,45.8,45.9,47.2,48.6,48.8,43.137500
CH,122.8,126.6,131.8,133.1,131.2,133.6,133.2,134.3,135.0,136.1,135.3,132.8,130.8,131.4,129.1,129.3,131.650000
CY,83.9,85.2,85.9,86.3,86.0,83.1,80.9,79.2,77.9,76.1,76.5,78.1,77.6,77.0,76.6,74.4,80.293750
CZ,70.4,71.0,74.0,74.1,74.7,72.1,71.8,71.4,72.2,73.9,75.3,74.5,75.8,76.5,77.9,77.7,73.956250
DE,128.9,126.5,126.0,124.7,122.9,122.3,123.7,123.1,122.6,124.5,123.0,124.7,124.9,124.8,122.2,121.8,124.162500
DK,126.9,126.7,126.2,127.8,129.0,135.2,132.6,132.9,132.9,134.1,133.8,133.7,136.2,137.8,136.9,139.3,132.625000
EA,116.9,116.5,115.6,114.8,113.8,112.9,112.1,112.0,112.2,111.8,111.0,111.0,110.6,109.8,109.2,109.9,112.506250
EA19,114.0,113.7,113.2,112.7,112.5,111.7,111.2,111.1,111.3,111.4,111.0,111.0,110.6,109.8,109.2,109.9,111.518750
EE,50.7,52.4,57.2,57.3,60.6,63.0,62.5,64.2,64.5,66.1,63.6,64.8,65.5,69.9,71.1,72.4,62.862500
EL,78.4,80.9,79.1,79.4,78.6,72.8,66.0,63.3,62.8,62.0,62.7,59.0,58.9,55.9,56.7,56.1,67.037500
ES,98.3,100.4,100.8,100.1,102.3,99.7,98.3,100.1,100.4,100.3,98.9,98.4,98.2,95.8,94.7,92.6,98.706250
EU27_2020,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.000000
EU28,101.7,101.6,101.3,101.3,100.9,101.0,100.6,100.5,100.3,100.2,100.3,99.9,99.8,99.6,99.6,NaN,100.573333
FI,115.5,114.6,118.4,118.8,115.9,114.9,114.6,111.6,110.2,109.8,109.7,110.6,111.8,110.3,108.0,107.9,112.662500
FR,132.3,132.5,130.2,128.2,128.0,126.9,125.6,123.5,125.6,125.5,124.8,124.5,124.2,124.0,126.0,126.5,126.768750
HR,59.3,61.2,62.8,63.4,60.7,59.4,62.1,64.1,65.5,63.5,65.6,66.8,67.0,67.0,65.8,60.2,63.400000
HU,63.2,63.5,64.4,68.1,69.6,70.1,71.3,69.6,69.4,67.3,67.0,63.5,63.4,65.5,66.6,68.1,66.912500
IE,126.1,126.8,127.3,119.9,123.9,136.7,138.6,139.9,134.4,136.9,174.5,169.0,171.9,176.7,176.7,189.1,148.025000
IS,NaN,NaN,NaN,113.1,123.5,114.5,111.0,110.3,110.0,110.9,114.0,114.1,112.8,112.6,115.7,111.4,113.376923
IT,109.0,107.8,107.2,108.3,108.2,106.4,105.9,105.6,104.4,103.0,101.7,103.2,101.9,100.9,100.4,102.1,104.750000
LT,49.1,51.7,54.5,56.2,53.8,58.3,62.5,63.6,64.9,65.4,63.0,61.5,65.4,66.3,67.9,69.9,60.875000
LU,183.9,192.7,191.7,191.3,189.3,188.5,187.2,186.9,188.6,191.8,190.7,189.9,184.1,178.0,172.1,175.9,186.412500
LV,42.3,42.5,45.5,47.9,48.4,51.1,50.9,53.8,53.1,54.7,55.8,56.6,58.3,59.0,60.2,59.9,52.500000
MT,76.1,73.2,74.0,73.4,73.0,76.5,74.2,75.1,75.7,78.1,82.6,78.6,81.6,79.4,75.9,71.7,76.193750
NL,142.2,142.3,141.9,142.3,137.5,134.9,132.8,132.7,133.8,130.6,129.6,126.3,125.5,124.8,122.5,122.2,132.618750
NO,184.7,191.1,181.8,188.5,172.1,174.4,177.8,181.1,178.9,172.3,154.8,144.8,151.6,158.4,146.7,135.8,168.425000
PL,50.3,49.5,50.3,50.9,53.0,57.2,59.1,59.8,59.3,59.0,59.6,59.4,60.3,62.5,64.7,63.6,57.406250
PT,69.1,70.4,69.6,69.6,70.1,70.2,67.9,68.4,70.4,69.3,68.3,67.9,66.2,65.6,65.6,65.8,68.400000
RO,33.0,36.9,40.5,47.7,48.5,48.1,49.1,50.5,51.0,52.0,53.7,57.2,60.4,62.6,65.4,64.2,51.300000
SE,122.8,125.0,126.4,124.5,121.9,120.8,120.1,119.9,117.5,116.7,118.0,114.1,112.4,111.6,112.5,113.5,118.606250
SI,83.8,84.8,85.1,84.9,79.6,79.1,80.9,80.9,80.0,79.5,78.3,80.5,82.3,83.8,83.8,83.1,81.900000
SK,67.0,69.5,72.3,75.2,74.3,78.3,76.5,76.8,77.7,78.4,78.1,72.7,70.4,69.8,69.6,72.0,73.662500

In [48]:
country_name= []
for geo in df_productivity.index:
    if geo=='AT':
        df_productivity = df_productivity.rename(index={'AT': 'AUT'})
        country_name.append('Austria')
    if geo=='BE':
        df_productivity = df_productivity.rename(index={'BE': 'BEL'})
    if geo=='CH':
        df_productivity = df_productivity.rename(index={'CH': 'CHE'})
    if geo=='CZ':
        df_productivity = df_productivity.rename(index={'CZ': 'CZE'})       
    if geo=='DE':
        df_productivity = df_productivity.rename(index={'DE': 'DEU'})
    if geo=='DK':
        df_productivity = df_productivity.rename(index={'DK': 'DNK'})
    if geo=='EE':
        df_productivity = df_productivity.rename(index={'EE': 'EST'})
    if geo=='EL':
        df_productivity = df_productivity.rename(index={'EL': 'GRC'})        
    if geo=='ES':
        df_productivity = df_productivity.rename(index={'ES': 'ESP'})
    if geo=='FI':
        df_productivity = df_productivity.rename(index={'FI': 'FIN'})
    if geo=='FR':
        df_productivity = df_productivity.rename(index={'FR': 'FRA'})
    if geo=='HU':
        df_productivity = df_productivity.rename(index={'HU': 'HUN'})
    if geo=='IE':
        df_productivity = df_productivity.rename(index={'IE': 'IRL'})
    if geo=='IT':
        df_productivity = df_productivity.rename(index={'IT': 'ITA'})       
    if geo=='LT':
        df_productivity = df_productivity.rename(index={'LT': 'LTU'})
    if geo=='LU':
        df_productivity = df_productivity.rename(index={'LU': 'LUX'})
    if geo=='NL':
        df_productivity = df_productivity.rename(index={'NL': 'NLD'})
    if geo=='NO':
        df_productivity = df_productivity.rename(index={'NO': 'NOR'})
    if geo=='PL':
        df_productivity = df_productivity.rename(index={'PL': 'POL'})
    if geo=='PT':
        df_productivity = df_productivity.rename(index={'PT': 'PRT'})
    if geo=='SE':
        df_productivity = df_productivity.rename(index={'SE': 'SWE'})
    if geo=='SI':
        df_productivity = df_productivity.rename(index={'SI': 'SVK'})        
    if geo=='SK':
        df_productivity = df_productivity.rename(index={'SK': 'SVN'})

In [49]:
df_productivity.shape

(34, 17)

In [50]:
import pandas as pd
education = pd.read_csv(r'/home/katia/Downloads/datasets/Educational_attainment_and_labour-force_status.csv')
education
education = education[['COUNTRY','Country', 'ISCED 2011 A education level','Reference year', 'Value']]
education

,COUNTRY,Country,ISCED 2011 A education level,Reference year,Value
0,DEU,Germany,Below upper secondary education,2014,0.055818
1,DEU,Germany,Below upper secondary education,2015,0.055701
2,DEU,Germany,Below upper secondary education,2016,0.054117
3,DEU,Germany,Below upper secondary education,2017,0.053313
4,DEU,Germany,Below upper secondary education,2018,0.053377
...,...,...,...,...,...
1912,ESP,Spain,Tertiary education,2016,35.693489
1913,ESP,Spain,Tertiary education,2017,36.351273
1914,ESP,Spain,Tertiary education,2018,37.252804
1915,ESP,Spain,Tertiary education,2019,38.596992
1916,ESP,Spain,Tertiary education,2020,39.686920

In [51]:
tertiary_education = education[(education['ISCED 2011 A education level']== 'Tertiary education')]
tertiary_education = tertiary_education[['COUNTRY','Country','Reference year', 'Value']]
tertiary_education 
df_tertiary_education = tertiary_education.pivot_table('Value',['COUNTRY'],'Reference year' )
df_tertiary_education

Reference year,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
COUNTRY,,,,,,,,,,,,,,,,
AUT,12.384059,12.744005,12.611729,13.163426,13.517386,13.942734,14.049184,14.441409,14.941533,15.025593,15.349697,15.765939,16.271159,16.430742,16.962326,17.178454
BEL,31.045088,31.754845,32.094864,32.310043,33.397053,34.989502,34.612984,35.316551,35.535332,18.528958,18.533002,18.855942,20.214313,20.405984,20.420567,21.308823
CHE,28.763943,29.851349,31.327906,33.652287,17.642706,17.022660,17.078790,17.724113,18.784361,19.297079,19.975724,20.704877,21.384457,21.959561,22.294802,22.726317
CZE,13.058269,13.522043,13.732669,14.498895,15.544437,16.764982,18.243177,9.750387,10.346138,10.815234,11.154889,11.548565,12.028002,12.196742,12.172790,12.495951
DEU,24.552816,23.947578,24.299988,25.400061,26.385326,26.609148,27.562323,28.121572,28.473270,13.565694,13.855903,14.181501,14.326953,14.568226,14.985995,15.667310
DNK,33.544121,34.719662,30.903458,15.657129,16.096084,16.601348,16.934427,17.423578,17.707036,17.937111,18.387478,18.994181,19.554886,19.832018,20.286762,NaN
E22,24.025146,24.717791,25.175871,27.069641,28.330649,27.728856,28.633746,29.636128,30.520005,31.430713,32.024872,32.985475,33.815401,34.714032,35.897734,36.976354
ESP,14.298571,14.443123,14.675973,14.797334,15.032201,15.545959,15.995474,16.363400,16.906225,17.378734,17.580627,17.887589,18.216797,18.667453,19.339713,19.886741
EST,16.753248,16.786845,16.785740,17.306357,18.266105,17.942275,18.667722,19.010774,18.880406,18.957535,19.225193,19.589643,20.029146,20.760363,20.879019,21.296262
FIN,34.629433,35.141739,36.357056,36.583557,37.268574,38.146343,39.318207,39.661289,40.545231,20.973197,21.523516,21.893290,22.249681,22.693243,23.068151,24.040793
FRA,25.425774,26.183411,26.646099,27.233906,28.588057,29.006897,16.320801,16.900543,16.100182,16.818501,17.089170,17.337713,17.654317,18.497022,19.001634,19.915365
GBR,29.709032,34.191841,35.536041,35.216167,36.984959,38.187191,39.412373,40.977753,41.891979,21.217836,22.211578,22.998472,22.986509,23.009301,23.714628,24.825306
GRC,10.786544,11.266608,11.499821,11.821548,11.881583,12.425898,13.113644,13.421438,13.773655,14.116476,14.593964,15.179686,15.578847,15.937061,16.015162,16.447062
HUN,17.083904,17.699047,18.048761,19.197906,19.862190,20.121918,21.124001,22.046715,11.309226,11.735556,12.180871,11.917294,12.089115,12.615782,13.058606,13.671792
IRL,29.074234,31.095585,32.390110,33.902611,35.822323,37.584061,38.162312,39.697880,41.470680,40.967049,21.482803,22.725579,22.920752,23.562930,23.747554,25.074345
ITA,12.224514,12.872448,13.578119,14.357011,14.510798,14.802574,14.935372,7.886640,8.177782,8.489099,8.807868,8.897053,9.370940,9.698596,9.853493,10.106674
LTU,13.414389,26.751383,28.931429,30.408518,30.958277,16.343660,33.489258,34.053780,35.198330,36.668087,19.496524,20.001393,20.268109,20.958235,21.710039,22.213725
LUX,26.549366,23.993208,26.512686,27.653927,34.795971,35.475895,37.034779,39.110382,40.673241,23.253975,20.084244,21.663196,20.373610,22.078652,26.164378,25.991583
NLD,30.115440,30.189871,30.803967,32.167362,32.785397,32.389164,32.041344,34.398335,33.869305,34.419815,35.330765,35.999168,37.168110,19.219595,20.241061,21.374334
NOR,32.692787,32.926327,34.198307,36.004189,36.698498,37.284328,38.053513,38.561893,39.770252,20.985602,21.460773,21.614481,21.707825,21.891530,22.168959,22.740534
POL,16.926928,17.891872,18.688519,19.565832,21.150869,22.468407,23.283596,24.512804,25.755669,26.995474,27.747267,28.711193,29.919453,30.919592,16.073413,16.500863
PRT,12.844431,13.480192,13.692096,14.300379,14.666820,15.445285,17.257030,18.534111,19.307142,10.927370,11.499176,11.996375,12.093883,12.568901,13.222388,14.173195
SVK,14.004099,14.567307,14.438412,14.763523,15.762831,17.327984,18.617317,18.979084,19.877340,10.362724,10.754211,11.172646,11.738809,12.488146,13.095333,13.595998
SVN,20.171976,21.387041,22.227602,22.637665,23.315817,23.716619,25.090590,26.439035,27.880541,28.600916,15.209357,30.735788,34.302807,16.351755,33.283279,18.072986
SWE,29.645443,15.317107,15.721952,16.072195,16.584919,16.987510,35.174355,17.908783,18.573998,19.409006,19.954236,20.632186,21.031075,21.698294,22.077639,22.391081
TUR,10.238610,10.919287,11.290907,12.040659,12.710275,13.118464,14.034094,15.290227,15.907355,16.693634,18.020138,19.362528,20.013071,20.780222,21.951159,NaN

In [52]:
average_education = education[(education['ISCED 2011 A education level']== 'Upper secondary or post-secondary non-tertiary education')]
average_education =average_education[['COUNTRY','Country','Reference year', 'Value']]
average_education 
df_average_education = average_education.pivot_table('Value',['COUNTRY'],'Reference year' )
df_average_education

Reference year,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
COUNTRY,,,,,,,,,,,,,,,,
AUT,26.227419,27.461246,27.497280,27.420448,27.452582,27.383202,27.282423,27.166917,26.695289,27.055182,27.129401,26.651750,26.362938,26.372878,25.974882,25.805935
BEL,35.051159,35.187229,35.858559,37.266140,37.175842,35.510010,36.653725,36.327080,37.223022,18.449168,19.014673,18.899117,18.354313,18.879628,19.092536,18.755208
CHE,56.482964,55.548450,54.629665,53.155655,26.087238,25.662373,25.494613,25.269135,24.584894,24.482761,23.842302,23.188457,22.694603,22.415931,22.385763,22.088623
CZE,76.867134,76.757668,76.802109,76.404411,75.858459,75.177650,74.089088,36.711523,36.309000,35.905957,35.553230,35.295733,35.002158,34.869760,34.841563,34.673562
DEU,58.554329,59.289337,60.115101,59.931107,59.094433,59.201168,58.688049,58.179337,57.847530,29.963319,29.616940,29.131411,29.007655,28.843832,28.450079,27.467827
DNK,47.472664,46.920448,43.374550,22.087858,22.031925,21.959230,22.266028,22.205446,22.100058,21.746461,21.684717,21.367293,21.140833,20.914656,20.728038,NaN
E22,47.841728,48.146016,48.003964,45.990447,46.002921,48.961370,48.712818,48.518431,48.572016,47.755921,47.471128,47.330911,46.843014,46.565097,45.829106,45.674250
ESP,10.153687,10.473960,10.716323,10.824866,10.851332,10.961764,11.096390,11.036875,10.893632,11.003636,11.211383,11.325864,11.397456,11.467165,11.394031,11.626471
EST,28.070906,27.821914,28.071648,27.294168,26.546076,27.096722,26.290960,26.373295,26.801100,25.516871,25.479685,25.286124,24.710990,24.227420,24.541875,24.415973
FIN,44.158085,44.494862,44.152626,44.489677,44.704552,44.836487,44.406101,45.135994,45.345337,22.450655,22.357993,22.252267,21.997220,22.041728,22.265407,21.771294
FRA,41.384293,41.245548,41.821098,42.364265,41.666153,41.759781,22.474426,22.410916,21.420860,21.941195,21.772136,21.811343,21.634723,21.280694,21.317009,20.943185
GBR,37.122650,36.709263,36.656673,36.424484,36.758167,36.875210,37.420158,37.107475,37.258495,18.580419,17.818266,17.600280,17.822070,16.867681,16.548534,16.251499
GRC,18.179960,18.469418,18.653537,18.947153,18.979866,19.055889,19.285156,19.599769,19.953911,20.149742,20.651898,20.777841,20.910311,20.885854,21.107067,21.905337
HUN,59.306282,60.374454,61.157066,60.505455,60.712025,61.170437,60.643833,60.073402,30.060221,29.935835,29.555602,29.894419,30.057284,29.954057,29.572136,29.262974
IRL,35.459042,35.248314,35.336098,35.550751,35.345600,35.190754,35.472363,34.935005,35.255356,37.845661,18.583469,18.458233,18.261371,18.211569,18.265806,17.872468
ITA,37.861622,38.416656,38.721588,38.955219,39.790382,40.371780,41.093086,20.808358,20.977488,21.242673,21.217381,21.255408,21.168687,21.257861,21.311393,21.411025
LTU,30.631924,61.569172,59.999691,60.142979,60.360397,29.859066,59.377556,59.270020,58.244312,54.507820,26.453675,26.529315,26.410565,25.794224,25.194008,24.896601
LUX,39.304268,41.527729,39.222908,40.287777,42.548435,42.201790,40.222870,39.192108,39.813763,18.296212,17.588565,18.209645,18.392670,16.802629,12.042148,11.700569
NLD,41.703503,42.175610,42.379169,41.124588,40.610600,40.584415,40.242668,39.025169,41.925877,41.481617,41.068810,41.067532,41.213829,20.387794,19.635289,19.240206
NOR,44.520832,45.969803,44.727242,44.717346,44.025360,43.343231,43.842903,43.492111,42.638336,20.200724,19.938788,19.715748,19.483804,19.552771,19.297299,18.704911
POL,68.185944,67.920158,67.613113,67.583122,66.821266,66.046318,65.629021,65.084984,64.378479,63.521564,63.030708,62.609581,62.191849,61.528210,30.377927,30.250738
PRT,13.606074,14.129419,13.763488,13.947564,15.237852,16.472258,17.770487,19.095991,20.740372,10.850541,11.202486,11.602575,12.030964,12.489489,13.025863,13.706283
SVK,73.865288,74.242401,74.720940,75.170403,75.182259,73.637230,72.644165,72.735786,71.922043,35.425500,35.268598,35.087584,34.313920,33.712255,32.932089,33.064623
SVN,60.124180,60.176327,59.590744,59.405548,59.970695,59.593433,59.385700,58.533745,57.572769,57.124428,28.439009,56.608772,53.379494,27.972766,55.513828,27.316581
SWE,53.946407,26.839210,26.691870,26.570209,26.397645,26.257823,51.860733,25.963506,25.626751,21.487061,21.156189,20.856861,20.592398,20.093793,19.922329,19.730997
TUR,17.843439,18.225998,18.300762,18.267813,18.344694,18.087578,18.114084,18.573956,18.924805,18.939352,18.972311,19.150930,19.278526,19.456722,19.748970,NaN

In [53]:
low_education = education[(education['ISCED 2011 A education level']== 'Below upper secondary education')]
low_education = low_education[['COUNTRY','Country','Reference year', 'Value']]
low_education 
df_low_eduction = low_education.pivot_table('Value',['COUNTRY'],'Reference year' )
df_low_eduction[""]

Reference year,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
COUNTRY,,,,,,,,,,,,,,,,
AUT,11.590464,9.996147,10.091848,9.620413,9.238142,8.884093,8.878803,8.601176,8.573297,8.130781,7.733826,7.793430,7.575281,7.407897,7.273991,7.226450
BEL,33.903755,33.057926,32.046577,30.423817,29.427107,29.500488,28.733294,28.356371,27.241648,13.317427,12.755461,12.545786,11.675235,10.959469,10.728231,10.180709
CHE,14.753095,14.600200,14.042429,13.192060,6.635358,7.545117,7.647962,7.225088,6.852146,6.444951,6.409817,6.340732,6.153492,5.855788,5.552274,5.414326
CZE,10.074598,9.720290,9.465225,9.096694,8.597104,8.057369,7.667735,3.849186,3.664265,3.441843,3.457981,3.323593,3.139483,3.106498,3.161411,3.011269
DEU,16.892855,16.763083,15.584911,14.668834,14.520243,14.189683,13.749630,13.699094,13.679199,6.576200,6.632225,6.788815,6.765851,6.689099,6.665367,6.977058
DNK,18.983217,18.359888,25.721992,12.537405,12.156299,11.734875,11.100998,10.672018,10.495470,10.615182,10.227782,9.954273,9.615069,9.557013,9.292032,NaN
E22,28.133126,27.136193,26.820164,26.939912,25.666430,23.309775,22.653435,21.845441,20.907980,20.813366,20.504000,19.683613,19.341585,18.720871,18.273160,17.349396
ESP,25.665140,25.198243,24.720945,24.490763,24.228351,23.604122,23.021173,22.712826,22.313611,21.732158,21.324489,20.905076,20.504839,19.983667,19.384181,18.610141
EST,5.833116,6.014361,5.722135,5.994072,5.817783,5.582407,5.639312,5.167221,4.866075,6.086295,5.858679,5.688432,5.786301,5.528266,5.090153,4.785991
FIN,21.212481,20.363401,19.490316,18.926767,18.026873,17.017170,16.275690,15.202716,14.109433,6.805341,6.526518,6.108821,6.011669,5.525265,4.928104,4.453186
FRA,33.189934,32.571041,31.532801,30.401829,29.745792,29.233322,15.610067,15.155613,12.621084,11.384191,11.274737,10.986256,10.848424,10.360504,9.821127,9.300322
GBR,33.168320,29.098894,27.807289,28.359348,26.256872,24.937599,23.167467,21.914770,20.849527,10.507205,10.282488,9.717595,9.505309,10.450064,10.065978,9.275614
GRC,21.203854,20.438008,20.023200,19.408204,19.313512,18.691744,17.785345,17.175008,16.467909,15.932741,14.955729,14.237565,13.707980,13.378993,13.087593,11.869899
HUN,23.609816,21.926500,20.794170,20.296638,19.425785,18.707645,18.232164,17.879883,8.804179,8.503756,8.443495,8.371939,8.040101,7.622978,7.568460,7.268666
IRL,35.466724,33.656101,32.273792,30.546635,28.832077,27.225185,26.365326,25.367115,23.273964,21.187292,10.155974,9.292348,9.067659,8.484199,8.241186,7.325645
ITA,49.913864,48.710896,47.700294,46.687767,45.698818,44.825645,43.971539,21.425730,20.965663,20.390922,20.099023,19.973630,19.587451,19.171458,18.964326,18.616125
LTU,6.354414,11.679444,11.068882,9.448503,8.681327,4.122657,7.133187,6.676203,6.557359,8.824093,4.399684,3.814816,3.654972,3.579100,3.436385,3.251024
LUX,34.146366,34.479065,34.264404,32.058296,22.655592,22.322315,22.742352,21.697510,19.512997,9.232439,12.861932,10.784619,11.832746,11.496671,12.723842,13.218811
NLD,28.181055,27.634520,26.816864,26.708052,26.604006,27.026423,27.715986,26.576496,24.204819,24.098568,23.600424,22.933300,21.618059,10.528294,10.260241,9.529426
NOR,22.786383,21.103868,21.074450,19.278467,19.276142,19.372442,18.103582,17.945995,17.591412,9.109514,8.896809,8.962408,9.096223,8.840624,8.819832,8.838671
POL,14.887128,14.187970,13.698365,12.851042,12.027865,11.485272,11.087381,10.402209,9.865854,9.482964,9.222026,8.679227,7.888699,7.552199,3.720817,3.411389
PRT,73.549492,72.390388,72.544418,71.752060,70.095329,68.082458,64.972481,62.369896,59.952484,28.442571,27.521986,26.630682,26.110080,25.183535,24.003160,22.402225
SVK,12.130613,11.190296,10.840645,10.066078,9.054909,9.034791,8.738519,8.285130,8.200620,4.704419,4.481187,4.246995,4.477325,4.337252,4.525475,3.898027
SVN,19.703846,18.436632,18.181656,17.956785,16.713486,16.689947,15.523709,15.027221,14.546692,14.274657,6.697366,12.655440,12.317700,6.017092,11.202892,4.962439
SWE,16.408150,8.007393,7.750917,7.523914,7.171346,6.902254,12.964911,6.289807,5.952850,9.269446,9.059918,8.684331,8.549549,8.412569,8.252283,8.113865
TUR,71.917953,70.854713,70.408333,69.691528,68.945030,68.793961,67.851822,66.135818,65.167839,64.367012,63.007553,61.486542,60.708405,59.763054,58.299870,NaN

In [54]:
df_education = education.pivot_table('Value',['COUNTRY', 'ISCED 2011 A education level'],'Reference year' )
df_education

Reference year                                                   2005  \
COUNTRY ISCED 2011 A education level
AUT     Below upper secondary education                     11.590464
        Tertiary education                                  12.384059
        Upper secondary or post-secondary non-tertiary ...  26.227419
BEL     Below upper secondary education                     33.903755
        Tertiary education                                  31.045088
...                                                               ...
SWE     Tertiary education                                  29.645443
        Upper secondary or post-secondary non-tertiary ...  53.946407
TUR     Below upper secondary education                     71.917953
        Tertiary education                                  10.238610
        Upper secondary or post-secondary non-tertiary ...  17.843439

Reference year                                                   2006  \
COUNTRY ISCED 2011 A education level
AUT     Below upper secondary education                      9.996147
        Tertiary education                                  12.744005
        Upper secondary or post-secondary non-tertiary ...  27.461246
BEL     Below upper secondary education                     33.057926
        Tertiary education                                  31.754845
...                                                               ...
SWE     Tertiary education                                  15.317107
        Upper secondary or post-secondary non-tertiary ...  26.839210
TUR     Below upper secondary education                     70.854713
        Tertiary education                                  10.919287
        Upper secondary or post-secondary non-tertiary ...  18.225998

Reference year                                                   2007  \
COUNTRY ISCED 2011 A education level
AUT     Below upper secondary education                     10.091848
        Tertiary education                                  12.611729
        Upper secondary or post-secondary non-tertiary ...  27.497280
BEL     Below upper secondary education                     32.046577
        Tertiary education                                  32.094864
...                                                               ...
SWE     Tertiary education                                  15.721952
        Upper secondary or post-secondary non-tertiary ...  26.691870
TUR     Below upper secondary education                     70.408333
        Tertiary education                                  11.290907
        Upper secondary or post-secondary non-tertiary ...  18.300762

Reference year                                                   2008  \
COUNTRY ISCED 2011 A education level
AUT     Below upper secondary education                      9.620413
        Tertiary education                                  13.163426
        Upper secondary or post-secondary non-tertiary ...  27.420448
BEL     Below upper secondary education                     30.423817
        Tertiary education                                  32.310043
...                                                               ...
SWE     Tertiary education                                  16.072195
        Upper secondary or post-secondary non-tertiary ...  26.570209
TUR     Below upper secondary education                     69.691528
        Tertiary education                                  12.040659
        Upper secondary or post-secondary non-tertiary ...  18.267813

Reference year                                                   2009  \
COUNTRY ISCED 2011 A education level
AUT     Below upper secondary education                      9.238142
        Tertiary education                                  13.517386
        Upper secondary or post-secondary non-tertiary ...  27.452582
BEL     Below upper secondary education                     29.427107
        Tertiary education                                  33.397053
...                                                               ...
SWE     Tertiary education                                  16.584919
        Upper secondary or post-secondary non-tertiary ...  26.397645
TUR     Below upper secondary education                     68.945030
        Tertiary education                                  12.710275
        Upper secondary or post-secondary non-tertiary ...  18.344694

Reference year                                                   2010  \
COUNTRY ISCED 2011 A education level
AUT     Below upper secondary education                      8.884093
        Tertiary education                                  13.942734
        Upper secondary or post-secondary non-tertiary ...  27.383202
BEL     Below upper secondary education                     29.500488
        Tertiary education                                  34.989502
...                                                               ...
SWE     Tertiary education                                  16.987510
        Upper secondary or post-secondary non-tertiary ...  26.257823
TUR     Below upper secondary education                     68.793961
        Tertiary education                                  13.118464
        Upper secondary or post-secondary non-tertiary ...  18.087578

Reference year                                                   2011  \
COUNTRY ISCED 2011 A education level
AUT     Below upper secondary education                      8.878803
        Tertiary education                                  14.049184
        Upper secondary or post-secondary non-tertiary ...  27.282423
BEL     Below upper secondary education                     28.733294
        Tertiary education                                  34.612984
...                                                               ...
SWE     Tertiary education                                  35.174355
        Upper secondary or post-secondary non-tertiary ...  51.860733
TUR     Below upper secondary education                     67.851822
        Tertiary education                                  14.034094
        Upper secondary or post-secondary non-tertiary ...  18.114084

Reference year                                                   2012  \
COUNTRY ISCED 2011 A education level
AUT     Below upper secondary education                      8.601176
        Tertiary education                                  14.441409
        Upper secondary or post-secondary non-tertiary ...  27.166917
BEL     Below upper secondary education                     28.356371
        Tertiary education                                  35.316551
...                                                               ...
SWE     Tertiary education                                  17.908783
        Upper secondary or post-secondary non-tertiary ...  25.963506
TUR     Below upper secondary education                     66.135818
        Tertiary education                                  15.290227
        Upper secondary or post-secondary non-tertiary ...  18.573956

Reference year                                                   2013  \
COUNTRY ISCED 2011 A education level
AUT     Below upper secondary education                      8.573297
        Tertiary education                                  14.941533
        Upper secondary or post-secondary non-tertiary ...  26.695289
BEL     Below upper secondary education                     27.241648
        Tertiary education                                  35.535332
...                                                               ...
SWE     Tertiary education                                  18.573998
        Upper secondary or post-secondary non-tertiary ...  25.626751
TUR     Below upper secondary education                     65.167839
        Tertiary education                                  15.907355
        Upper secondary or post-secondary non-tertiary ...  18.924805

Reference year                                                   2014  \
COUNTRY ISCED 2011 A education level
AUT     Below upper secondary education                      8.130781
        Tertiary education                                  15.025593
        Upper secondary or post-secondary non-tertiary ...  27.055182
BEL     Below upper secondary education                     13.317427
        Tertiary education                                  18.528958
...                                                               ...
SWE     Tertiary education                                  19.409006
        Upper secondary or post-secondary non-tertiary ...  21.487061
TUR     Below upper secondary education                     64.367012
        Tertiary education                                  16.693634
        Upper secondary or post-secondary non-tertiary ...  18.939352

Reference year                                                   2015  \
COUNTRY ISCED 2011 A education level
AUT     Below upper secondary education                      7.733826
        Tertiary education                                  15.349697
        Upper secondary or post-secondary non-tertiary ...  27.129401
BEL     Below upper secondary education                     12.755461
        Tertiary education                                  18.533002
...                                                               ...
SWE     Tertiary education                                  19.954236
        Upper secondary or post-secondary non-tertiary ...  21.156189
TUR     Below upper secondary education                     63.007553
        Tertiary education                                  18.020138
        Upper secondary or post-secondary non-tertiary ...  18.972311

Reference year                                                   2016  \
COUNTRY ISCED 2011 A education level
AUT     Below upper secondary education                      7.793430
        Tertiary education                                  15.765939
        Upper secondary or post-secondary non-tertiary ...  26.651750
BEL     Below upper secondary education                     12.545786
        Tertiary education                                  18.855942
...                                                               ...
SWE     Tertiary education                                  20.632186
        Upper secondary or post-secondary non-tertiary ...  20.856861
TUR     Below upper secondary education                     61.486542
        Tertiary education                                  19.362528
        Upper secondary or post-secondary non-tertiary ...  19.150930

Reference year                                                   2017  \
COUNTRY ISCED 2011 A education level
AUT     Below upper secondary education                      7.575281
        Tertiary education                                  16.271159
        Upper secondary or post-secondary non-tertiary ...  26.362938
BEL     Below upper secondary education                     11.675235
        Tertiary education                                  20.214313
...                                                               ...
SWE     Tertiary education                                  21.031075
        Upper secondary or post-secondary non-tertiary ...  20.592398
TUR     Below upper secondary education                     60.708405
        Tertiary education                                  20.013071
        Upper secondary or post-secondary non-tertiary ...  19.278526

Reference year                                                   2018  \
COUNTRY ISCED 2011 A education level
AUT     Below upper secondary education                      7.407897
        Tertiary education                                  16.430742
        Upper secondary or post-secondary non-tertiary ...  26.372878
BEL     Below upper secondary education                     10.959469
        Tertiary education                                  20.405984
...                                                               ...
SWE     Tertiary education                                  21.698294
        Upper secondary or post-secondary non-tertiary ...  20.093793
TUR     Below upper secondary education                     59.763054
        Tertiary education                                  20.780222
        Upper secondary or post-secondary non-tertiary ...  19.456722

Reference year                                                   2019  \
COUNTRY ISCED 2011 A education level
AUT     Below upper secondary education                      7.273991
        Tertiary education                                  16.962326
        Upper secondary or post-secondary non-tertiary ...  25.974882
BEL     Below upper secondary education                     10.728231
        Tertiary education                                  20.420567
...                                                               ...
SWE     Tertiary education                                  22.077639
        Upper secondary or post-secondary non-tertiary ...  19.922329
TUR     Below upper secondary education                     58.299870
        Tertiary education                                  21.951159
        Upper secondary or post-secondary non-tertiary ...  19.748970

Reference year                                                   2020
COUNTRY ISCED 2011 A education level
AUT     Below upper secondary education                      7.226450
        Tertiary education                                  17.178454
        Upper secondary or post-secondary non-tertiary ...  25.805935
BEL     Below upper secondary education                     10.180709
        Tertiary education                                  21.308823
...                                                               ...
SWE     Tertiary education                                  22.391081
        Upper secondary or post-secondary non-tertiary ...  19.730997
TUR     Below upper secondary education                           NaN
        Tertiary education                                        NaN
        Upper secondary or post-secondary non-tertiary ...        NaN

[78 rows x 16 columns]

In [55]:
names = []
for name in (df_productivity.index):
    for name2 in (df_low_eduction.index):
        if name == name2:
            names.append(name)
            # print(name)
print(len(names))
# df_low_eduction

23

In [56]:

#df_low_eduction.shape
df_productivity = df_productivity.loc[names]
df_productivity

TIME_PERIOD,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,Average Productivity
geo,,,,,,,,,,,,,,,,,
AUT,117.5,117.8,116.8,116.3,117.5,115.6,115.1,118.0,117.9,118.1,119.7,119.5,117.5,117.8,115.9,117.4,117.40000
BEL,142.8,139.9,138.0,136.2,136.8,138.0,134.0,135.2,134.7,136.1,136.8,136.5,134.0,133.5,133.5,137.8,136.48750
CHE,122.8,126.6,131.8,133.1,131.2,133.6,133.2,134.3,135.0,136.1,135.3,132.8,130.8,131.4,129.1,129.3,131.65000
CZE,70.4,71.0,74.0,74.1,74.7,72.1,71.8,71.4,72.2,73.9,75.3,74.5,75.8,76.5,77.9,77.7,73.95625
DEU,128.9,126.5,126.0,124.7,122.9,122.3,123.7,123.1,122.6,124.5,123.0,124.7,124.9,124.8,122.2,121.8,124.16250
DNK,126.9,126.7,126.2,127.8,129.0,135.2,132.6,132.9,132.9,134.1,133.8,133.7,136.2,137.8,136.9,139.3,132.62500
EST,50.7,52.4,57.2,57.3,60.6,63.0,62.5,64.2,64.5,66.1,63.6,64.8,65.5,69.9,71.1,72.4,62.86250
GRC,78.4,80.9,79.1,79.4,78.6,72.8,66.0,63.3,62.8,62.0,62.7,59.0,58.9,55.9,56.7,56.1,67.03750
ESP,98.3,100.4,100.8,100.1,102.3,99.7,98.3,100.1,100.4,100.3,98.9,98.4,98.2,95.8,94.7,92.6,98.70625
FIN,115.5,114.6,118.4,118.8,115.9,114.9,114.6,111.6,110.2,109.8,109.7,110.6,111.8,110.3,108.0,107.9,112.66250
FRA,132.3,132.5,130.2,128.2,128.0,126.9,125.6,123.5,125.6,125.5,124.8,124.5,124.2,124.0,126.0,126.5,126.76875
HUN,63.2,63.5,64.4,68.1,69.6,70.1,71.3,69.6,69.4,67.3,67.0,63.5,63.4,65.5,66.6,68.1,66.91250
IRL,126.1,126.8,127.3,119.9,123.9,136.7,138.6,139.9,134.4,136.9,174.5,169.0,171.9,176.7,176.7,189.1,148.02500
ITA,109.0,107.8,107.2,108.3,108.2,106.4,105.9,105.6,104.4,103.0,101.7,103.2,101.9,100.9,100.4,102.1,104.75000
LTU,49.1,51.7,54.5,56.2,53.8,58.3,62.5,63.6,64.9,65.4,63.0,61.5,65.4,66.3,67.9,69.9,60.87500
LUX,183.9,192.7,191.7,191.3,189.3,188.5,187.2,186.9,188.6,191.8,190.7,189.9,184.1,178.0,172.1,175.9,186.41250
NLD,142.2,142.3,141.9,142.3,137.5,134.9,132.8,132.7,133.8,130.6,129.6,126.3,125.5,124.8,122.5,122.2,132.61875
NOR,184.7,191.1,181.8,188.5,172.1,174.4,177.8,181.1,178.9,172.3,154.8,144.8,151.6,158.4,146.7,135.8,168.42500
POL,50.3,49.5,50.3,50.9,53.0,57.2,59.1,59.8,59.3,59.0,59.6,59.4,60.3,62.5,64.7,63.6,57.40625
PRT,69.1,70.4,69.6,69.6,70.1,70.2,67.9,68.4,70.4,69.3,68.3,67.9,66.2,65.6,65.6,65.8,68.40000
SWE,122.8,125.0,126.4,124.5,121.9,120.8,120.1,119.9,117.5,116.7,118.0,114.1,112.4,111.6,112.5,113.5,118.60625
SVK,83.8,84.8,85.1,84.9,79.6,79.1,80.9,80.9,80.0,79.5,78.3,80.5,82.3,83.8,83.8,83.1,81.90000
SVN,67.0,69.5,72.3,75.2,74.3,78.3,76.5,76.8,77.7,78.4,78.1,72.7,70.4,69.8,69.6,72.0,73.66250

In [60]:
df_low_eduction = df_low_eduction.loc[names]
df_average_education = df_average_education.loc[names]
df_tertiary_education = df_tertiary_education.loc[names]

In [61]:

df_low_eduction['Average % Low Education'] = df_low_eduction.iloc[:,:16].mean(axis=1, skipna= True)
df_average_education['Average % Medium Education'] = df_average_education.iloc[:,:16].mean(axis=1, skipna= True)
df_tertiary_education['Average % Tertiary Education'] = df_tertiary_education.iloc[:,:16].mean(axis=1, skipna= True)

In [68]:
combine = df_low_eduction[['Average % Low Education']]
combine['Average % Medium Education']  = df_average_education[['Average % Medium Education']] 
combine['Average % Tertiary Education'] = df_tertiary_education[['Average % Tertiary Education']]
combine['Average Productivity'] = df_productivity['Average Productivity']

<ipython-input-68-a7822c2c25d0>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  combine['Average % Medium Education']  = df_average_education[['Average % Medium Education']]
<ipython-input-68-a7822c2c25d0>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  combine['Average % Tertiary Education'] = df_tertiary_education[['Average % Tertiary Education']]
<ipython-input-68-a7822c2c25d0>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  combine['Average Productivity'] = df_productivity['Average Productivity']

In [69]:
combine

Reference year,Average % Low Education,Average % Medium Education,Average % Tertiary Education,Average Productivity
COUNTRY,,,,
AUT,8.663503,26.871236,14.673711,117.40000
BEL,22.178331,28.606088,27.457741,136.48750
CHE,8.416552,31.750839,22.511933,131.65000
CZE,5.802159,53.194938,12.992073,73.95625
DEU,11.302634,45.836341,21.031479,124.16250
DNK,12.734901,26.533347,20.971952,132.62500
EST,5.591287,26.159108,18.821040,62.86250
GRC,16.729830,19.844544,13.616187,67.03750
ESP,22.399983,11.027177,16.688495,98.70625
FIN,12.561484,34.803768,30.880831,112.66250
FRA,19.002315,29.202977,21.169962,126.76875
HUN,14.093511,45.139718,15.860168,66.91250
IRL,21.047576,29.080741,31.230050,148.02500
ITA,31.668947,29.116288,11.160561,104.75000
LTU,6.417628,43.077583,25.679071,60.87500
LUX,20.376872,29.834630,28.213068,186.41250
NLD,22.752283,37.116667,30.782065,132.61875
NOR,14.943551,33.385701,29.922487,168.42500
POL,10.028150,60.798311,22.944484,57.40625
PRT,49.750203,14.354482,14.125548,68.40000
SWE,8.707094,27.124611,20.573736,118.60625
SVK,7.388268,56.495318,14.471610,81.90000
SVN,13.806722,52.544251,24.338986,73.66250

In [72]:
cor = combine.corr()

In [73]:
cor

Reference year,Average % Low Education,Average % Medium Education,Average % Tertiary Education,Average Productivity
Reference year,,,,
Average % Low Education,1.000000,-0.522107,-0.090733,0.105597
Average % Medium Education,-0.522107,1.000000,0.087843,-0.291824
Average % Tertiary Education,-0.090733,0.087843,1.000000,0.567161
Average Productivity,0.105597,-0.291824,0.567161,1.000000